### ISSUE TITLE
tensorboard --help sets an exit value of 1

### ISSUE THREAD

**Issue by jjhelmus** [tensorflow/tensorboard#1007]
Running the command `tensorboard --help` set an exit value of 1.  Non-zero exit values are typically used to indicate and error state but the command completed successfully.

Tested with tensorboard (1.5.1) and tensorflow (1.6.0rc1)

**Comment by nfelt** [comment]
Thanks for the report.  We use `tf.app.run()` from TensorFlow which with TF 1.5.0+ no longer uses argparse, so it defines its own help flag and has it sys.exit(1):
https://github.com/tensorflow/tensorflow/blob/v1.6.0-rc1/tensorflow/python/platform/app.py#L79

I don't think we'd want to diverge from the `tf.app.run()` default behavior, so fixing this would involve an upstream change.  If you're up for it, opening a bug with TensorFlow and framing it as a regression might be fastest, otherwise we can look into taking this up when we have time.

**Comment by jjhelmus** [comment]
@nfelt Thanks for the link, I was trying to track down where the exit value was being generated, but could not find it.  

I agree that this should be fixed in TensorFlow rather than here, I'll open an issue there.

**Comment by nfelt** [comment]
SGTM and thanks - feel free to cc me on that issue.
