### ISSUE TITLE
CTRL+C not working with debugger_port

### ISSUE THREAD

**Issue by fru** [tensorflow/tensorboard#1016]
Hey,
once I specify the debugger_port, closing tensorboard with ctrl + c will not work anymore. For me, this is just a little annoying and doesnt stop me from using this awesome new feature. Thanks :-)

**Comment by nfelt** [comment]
Thanks for the report and glad you're enjoying the debugger plugin! cc @caisq :)

Closing since the CTRL+C issue should have been more or less fixed by https://github.com/tensorflow/tensorboard/pull/975 (with some caveats/edge cases, see PR for details).  The fix will make it into the 1.7 release which should go out next week - in the mean time it should also be in our nightly build `tb-nightly`.  If you are stuck using 1.6 for some reason we could also consider backporting the fix and doing a 1.6.1 bugfix release.
