### ISSUE TITLE
Non functional tensorboard in latest tb-nightly build.

### ISSUE THREAD

**Issue by robieta** [tensorflow/tensorboard#1032]
Running tensorboard version 1.7.0a20180309 (latest at the time of writing) produces the following error.

```
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 7, in <module>
    from tensorboard.main import run_main
  File "/usr/local/lib/python3.5/dist-packages/tensorboard/main.py", line 30, in <module>
    from tensorboard import default
  File "/usr/local/lib/python3.5/dist-packages/tensorboard/default.py", line 36, in <module>
    from tensorboard.plugins.beholder import beholder_plugin
  File "/usr/local/lib/python3.5/dist-packages/tensorboard/plugins/beholder/beholder_plugin.py", line 30, in <module>
    from tensorboard.plugins.beholder import im_util
  File "/usr/local/lib/python3.5/dist-packages/tensorboard/plugins/beholder/im_util.py", line 94, in <module>
    colormaps = np.load('{}/colormaps.npy'.format(resources_path()))
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 372, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/tensorboard/plugins/beholder/resources/colormaps.npy'
```

This error is observed in both python2.7 and python3.5. The system is Ubuntu 16.04, running ResNet (tensorflow/models/official/resnet) on ImageNet. Reverting to tb-nightly==1.7.0a20180301 resolves the issue.

**Comment by nfelt** [comment]
Thanks for the report!  This looks like probably an issue with #1018.

**Comment by chrisranderson** [comment]
Downloading the resources directory fixed it for me.

**Comment by nfelt** [comment]
@chrisranderson thanks.  Just curious, is the colormaps.npy file in .npy format just to save space or was there some other reason?

Also FYI, not sure if you saw on #1018 but if you're interested in upstreaming the beholder README.md, it'd be great to have it in the Beholder plugin directory so we can point users to it and keep it in sync with any changes that accrue to the merged copy of Beholder.

**Comment by chrisranderson** [comment]
If there was some other reason, I don't know if it was a good one. :) Seems like my reasoning was that I just didn't want it inline in a file. Sorry that you all have to deal with my mistakes!

You can grab the README if you'd like - I'm not sure what my company's policies are about contributing to open source, and I'd hate if something as simple as submitting a PR for a README caused problems. I don't know what you mean by "upstreaming".

**Comment by chrisranderson** [comment]
Also, I couldn't find it looking just barely, but there was a problem with Beholder using Windows - a place where it should use `os.path.join` or something instead of assuming a forward slash for a path separator. That is almost totally useless, but better than me forgetting it entirely.

**Comment by nfelt** [comment]
Oh no this is our mistake I'm pretty sure - I think we just overlooked adding the resources file to the pip package build (haven't yet fully investigated).  We'd have needed to fix that even if colormaps was a regular .py file since there are also the images in that folder.

Ok, I understand re: the company policies, since that's actually why I was hoping you might be able to submit the README - even though it's not code per se it's probably clearer on our end to have it formally submitted (under the CLA).  I can ask around though, maybe that's fine.  We definitely don't want to cause issues for you either!  (And yeah, "upstreaming" probably isn't the right word...)

Re: the windows issue, maybe that's the line from the stacktrace in the OP? `np.load('{}/colormaps.npy'.format(resources_path()))`.  Should be easy enough to do `np.load(os.path.join(resources_path(), 'colormaps.npy'))` instead, thanks for mentioning it!

**Comment by chrisranderson** [comment]
Yeah that's exactly the line, thanks :) Weirdly, that's all I had to change. I thought I noticed stuff in the main Beholder file that wasn't right either. Shrug.
