### ISSUE TITLE
Tensorboard Image Rendering

### ISSUE THREAD

**Issue by neouyghur** [tensorflow/tensorboard#1113]
- TensorBoard version TensorBoard 0.1.8
 - TensorFlow version 1.3.0
 - OS Platform and version Linux Ubuntu 16.04
 - Python version Anaconda 3.6
 - For browser-related issues:
   - Browser type and version Version 65.0.3325.181 (Official Build) (64-bit)
   - Screenshot if it's a visual issue
 
Hi, I am rendering input, ground truth sample images in Tensorboard.  For some ground truth and input samples, the only difference is the text on the input image. In other words, for these cases, the background is totally same. However, I found ground-truth image backgrounds are changed during the rendering. To ensure, it is the problem of the tensorboard, I also print the difference of the input and grount-truth. 

I attached an screenshot here. You can check the group of {DIF/image/1, GTR/image/1, INP/image/1}. You will find out the input and groudtruth have different background color, but their differece image shows difference only the place where texts exist.

Another problem: the diff image only include two value: 1 and 0, but in diff image we can see other colors as well. 

I tested it both on firefox and chrome. It happens at both browser.

![untitled](https://user-images.githubusercontent.com/6363244/38486598-de579f0c-3c20-11e8-855d-4b11af422bc2.png)

**Comment by chihuahua** [comment]
When recording image summaries, TensorFlow normalizes colors of tensors based on the min and max float values of pixels. https://github.com/tensorflow/tensorflow/blob/bf170839d2a8be1b16e0a6c6a74ac2f0dc427f96/tensorflow/python/summary/summary.py#L123

This may be causing those color discrepancies. Perhaps one way to resolve this issue is to make sure that each image contains a min and max color value (ie, say 0 and 1). That way, TensorFlow will normalize each image along the same scale of float pixel values.

**Comment by nfelt** [comment]
The normalization doesn't happen if the tensor is of type uint8 (only float) so if you just convert to [0, 255] yourself that should allow you to avoid the normalization without modifying any pixel values.

**Comment by nfelt** [comment]
I'm going to close this out since it's a property of the original TensorFlow image summary API, and the workaround is conversion to uint8.  The newer TensorBoard image summary API doesn't do any normalization, to avoid this confusion.
