### ISSUE TITLE
Discrepancies in measurements of execution time between TensorBoard, timeline and time()

### ISSUE THREAD

**Issue by iurilarosa** [tensorflow/tensorboard#1195]
Hi, with Tensorflow 1.8.0 and TensorBoard 1.8.0 I have three different measurements of the execution time of my code. 
With the `time` function I get ~0.35 s, using it like the code below
```
start = time.time()
array = sess.run(tensor, feed_dict = dataDict)
stop = time.time()
stop-start
```
With TensorBoard I get ~0.08 s, using `timeline` i get ~0.1 s
The first measure is reliable because, for example, if I cycle the graph execution 100 times I have a total computing time ~35s.
Why these differences?

**Comment by jart** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
