### ISSUE TITLE
Zoom out

### ISSUE THREAD

**Issue by tazr** [tensorflow/tensorboard#1218]
- TensorBoard version (from pip package, also printed out when running `tensorboard`): 1.8.0
 
AFAIK the only way to zoom out is to click to the "Fit domain to data" button in the corner of a chart. However I sometimes find myself wanting to have a larger view than that.

For example, sometimes I want to have the y-axis starting at the value 0. This can give a better idea of the significance of improvements, depending on what is plotted.

Could this feature be considered for tensorboard?

**Comment by nfelt** [comment]
This sounds mostly like a duplicate of #77 (and see also #710), unless there's a specific use case for being able to dynamically "zoom out" with a zooming-style interaction, versus the various suggested approaches on those Github issues which mostly have an interaction more like "check box to start y-axis at 0" or "click button to enter explicit axis limits".

If you think it's not a duplicate feel free to elaborate, otherwise I'll consolidate and you can follow along on #77.

**Comment by tazr** [comment]
Having #77 would already be great, I am closing this one.
