### ISSUE TITLE
Beholder doesn't work in Eager Mode or TF 2.0

### ISSUE THREAD

**Issue by RanFeldesh** [tensorflow/tensorboard#1237]
Does Beholder works in Eager mode? If so, how should the call [beholder.update(
  session=sess)] be changed to support that? @chrisranderson , as the author, what is your opinion?

**Comment by nfelt** [comment]
Beholder doesn't currently support Eager mode - it has to be used with legacy graph mode.

It'd be possible with a relatively small amount of changes to make it work with eager mode for the use cases where it just emits raw numpy or image data (we would basically just convert the summary writing to avoid running any ops).  However, the popular feature where it visualizes trainable variables wouldn't really work at all because there is no default collection of trainable variables in Eager or in TF 2.0 more broadly.

**Comment by nfelt** [comment]
Closing this issue since we are intending to deprecate the Beholder plugin as described in #3843.  Please see that issue for recommendations if you want to keep using the plugin or adopt it yourself.
