### ISSUE TITLE
Scalar Graph zoom/scaling resets after update.

### ISSUE THREAD

**Issue by jubjamie** [tensorflow/tensorboard#125]
Using 1.2 from pip on Windows 10 fyi.

I've noticed that when you have a scalar graph zoomed in (i.e. zoom via box) that when Tensorboard updates/refreshes the data, the graph zooms out but **only** in the y-axis. The x axis remain scaled the same but the y-axis will return to it's full height. Because it only affects the one axis I presume that this is not intentional.
I've only noticed this with my current training session and haven't had a chance to try it with new data/server restart as I can't do that at the moment so I've included steps to reproduce below.
Hope that's clear, can clarify with pics or otherwise if required.

EDIT: Same happens when changing the smoothing.

**Quick steps to reproduce**

Launch a training session with some scalar summaries. Loss or whatever.
As it train, zoom in to a small rectangle area.
Wait or force refresh the data (not the page)
The scalar graph resets to full height.

Thanks

**Comment by wchargin** [comment]
Looks like we missed triaging this—sorry for the delay! Thanks for the clear report.

I can reproduce this issue in the 1.2 package from pip. Happily, it's fixed in current master: both reloading data and changing the smoothing factor (including disabling or enabling it completely) preserve your window settings.

(Changing the scale from linear to logarithmic (or vice versa) _does_ reset your window, as does changing whether outliers are ignored. This makes more sense, and we _do_ want to reset the window at least when you haven't changed it manually: perhaps it would be appropriate to have some logic along the lines of, "when the {log scale,outliers display} is toggled, reset the _y_ domain unless the user has dragged to a custom window and not since unzoomed." This would be more complicated.)

If you want to get the latest version, wherein this issue does not occur, [you'll want to build from source](https://github.com/tensorflow/tensorboard#usage). (You'll need [Bazel](https://bazel.build/).)

Does this resolve your issue?

**Comment by dandelionmane** [comment]
(Note - at the moment TensorBoard depends on TF nightly, so you'll need bazel and a very recent TensorFlow :) )

**Comment by rmothukuru** [comment]
@jubjamie ,
Can you please let us know if your issue is resolved. Thanks!

**Comment by jubjamie** [comment]
This was 2 years ago and I've since stopped using tensorboard so I'm not sure. I trust that the fix made a couple of years ago did the trick and happy to close the issue.
