### ISSUE TITLE
tensorflow 1.8.0 has requirement tensorboard<1.9.0,>=1.8.0, but you'll have tensorboard 1.6.0 which is incompatible.

### ISSUE THREAD

**Issue by isalirezag** [tensorflow/tensorboard#1255]
trying to instal the following comand:

`sudo -H pip install --upgrade tensorflow tensorflow-tensorboard`

and i got this error:

> tensorflow 1.8.0 has requirement tensorboard<1.9.0,>=1.8.0, but you'll have tensorboard 1.6.0 which is incompatible.

any help?

**Comment by nfelt** [comment]
The tensorboard pip package is now just `tensorboard`, you should `pip uninstall tensorflow-tensorboard` and then `pip install --upgrade tensorflow` by itself (which will automatically install the correct version of tensorboard).

**Comment by isalirezag** [comment]
@nfelt it gives me this error:

`tensorflow-gpu 1.5.0 requires tensorflow-tensorboard<1.6.0,>=1.5.0, which is not installed.
`

also whatever i do i dont know why i still cannot import tensorboard_logger

python -c "import tensorboard_logger"Traceback (most recent call last): File "<string>", line 1, in <module> ImportError: No module named tensorboard_logger

**Comment by NiRajlunavat** [comment]
Im allso getting the same error but did not find any solution

**Comment by nfelt** [comment]
@NiRajlunavat you'd need to provide more detail for us to be able to help.  Please make sure you're not installing tensorflow-tensorboard, which is the old package name, and also note that if you're using `tensorboard_logger` that's not affiliated with the official TensorBoard project.

**Comment by wxprofessor** [comment]
hopefully this will help? :)

After reading through some blogs about the tensorboard issue, I just uninstalled tensorflow, and protobuf (because of a previous incompatibility), and reinstalled tensorflow hoping the new dependencies would be found, and received the following.

![image](https://user-images.githubusercontent.com/5704029/43665555-8a811326-973e-11e8-983b-c8e8b53b62b3.png)

I then restarted the kernel in Jupyter Lab and ran a simple tensorflow gpu test to receive the original error I was trying to fix :)

![image](https://user-images.githubusercontent.com/5704029/43665604-c0dd211c-973e-11e8-8047-d8217f838e1b.png)

I found the potential fix for that here in the boards: https://github.com/tensorflow/tensorflow/issues/20778

that stated uninstalling and reinstalling might be a fix :)

Hopefully this might help to point to a potential resolution, as I repeatedly beat my head against the wall :)

**Comment by nfelt** [comment]
@wxprofessor It looks like your `pip install tensorflow` command is saying that you also have `tensorflow-gpu` installed - you want to only have one of the two installed at a time.  Can you try uninstalling all the tensor* packages and then reinstalling?  Or even better, get a fresh conda environment and try just installing tensorflow-gpu?

**Comment by wxprofessor** [comment]
oops... I was about to write another sample of uninstalling everything and getting a tensorboard conflict error.. but of course you are right, and I am shooting a giant potato at my tensor box lol :)  moment will post the results... I'm betting you are right.. tyvm :)

**Comment by wxprofessor** [comment]
Thank you @nfelt .. it worked exactly as you said :)  ^5

![image](https://user-images.githubusercontent.com/5704029/43666625-a00d481e-9742-11e8-8674-577a45a0ee50.png)

**Comment by nfelt** [comment]
@wxprofessor glad to hear it :)

**Comment by nfelt** [comment]
@NaderNazemi I'm not sure why, but that's not really something we can help with here (this is for TensorBoard issues only).  You can try asking on StackOverflow with the #tensorflow tag.

**Comment by NiRajlunavat** [comment]
Thanks for the support @nfelt ....its solved

**Comment by sunjiankun126** [comment]
Thank you @wxprofessor @nfelt ...

**Comment by vidyakabadi** [comment]
@nfelt  

![Screenshot (145)](https://user-images.githubusercontent.com/44683191/68534576-0f7dd200-035c-11ea-97c0-40eea40ee95b.png)

can you please help me in understanding like what that error is which is given  in red color in that screesshot??
**tensorboard 2.0.1 has requirement setuptools>=41.0.0, but you'll have setuptools 40.6.2 which is incompatible.**

**Comment by nfelt** [comment]
@vidyakabadi The error is what it says; `tensorboard` requires version 41.0.0 of `setuptools` or greater, and the version you have is only 40.6.2.  This is a general class of problem (updating `setuptools` in your python package environment) that isn't really specific to TensorBoard so there's a limit to which we can help.  You might try different ways to update your `setuptools` depending on where it's currently installed, e.g. https://stackoverflow.com/questions/36996629/sudo-pip-install-setuptools-upgrade-error

All this said, the red message doesn't actually prevent you from using TensorBoard, so if that's the only thing that happened and it otherwise works, you can just continue to use it.

**Comment by vidyakabadi** [comment]
Hi Nick thank you so much for replying so quickly
I am very happy to tell you that I resolved that warning by first updating
python  version and then updating tensorflow
It worked
