### ISSUE TITLE
404 error when used with a Jupyter proxy

### ISSUE THREAD

**Issue by hadim** [tensorflow/tensorboard#1270]
- TensorBoard 1.8.0 
- Tensorflow 1.8.0
- Linux Ubuntu 18.04
- Python 3.6
- Chromium 66

I am trying to use a Jupyter proxy called [`nbserverproxy`](https://github.com/jupyterhub/nbserverproxy) in order to access TB from the Jupyter server (that saves me one more SSH tunnel with the cluster).

TB interface loads correctly but can't retrieve information from `/data/runs`, `/data/environments`, and so forth. Opening the browser console shows a lot of 404 errors.

With `nbserverproxy` you access TB with the following URL: http://localhost:8888/proxy/6006. Looking at the browser console, TB seems to be looking for `http://localhost:8888/proxy/data/runs` instead of `http://localhost:8888/proxy/6006/data/runs`.

I tried a bunch of `--path_prefix`, `--base_url` and `--host` options, I can't get it to work.

I am not sure if it's a technical limitation, a bug from TB or something I am doing wrong.

Here is the associated issue on the nbserverproxy: https://github.com/jupyterhub/nbserverproxy/issues/41

**Comment by nfelt** [comment]
I think you might be seeing this due to a missing trailing slash in the URL you're using to visit TensorBoard - what happens if you try it with http://localhost:8888/proxy/6006/ including the trailing slash?  You might also need to pass --path_prefix=/proxy/6006/ depending on how nbserverproxy works (I'm not familiar with it).

Without the trailing slash, when tensorboard requests the relative path `data/runs` it's probably dropping the `6006` from `/proxy/6006` as though it were the filename and getting `/proxy/data/runs` instead.

**Comment by hadim** [comment]
Pretty easy fix indeed!!!

The trailing slash did the trick :-)

**Comment by nfelt** [comment]
Glad to hear that fixed it!

**Comment by canavandl** [comment]
thank you! thank you! thank you! @nfelt
