### ISSUE TITLE
[Feature Request] Night Mode Toggle Option

### ISSUE THREAD

**Issue by datlife** [tensorflow/tensorboard#1277]
It would be super helpful for people working at night like me.

Thanks,

**Comment by nfelt** [comment]
As a crude approximation of this, you can just invert the colors in the page by running `document.documentElement.style = "filter: invert(100%)"` in the JS console.

Doing this in a more sophisticated way seems tricky, because the various visualizations do different things in terms of color, background, etc.  For example, would you expect that a night mode would change how images on the Image dashboard get displayed (e.g. by tinting them orange) or would you expect it to preserve the original pixel values?  It could also be a bit tricky to define color palettes for the runs that show up well against a dark background (I'm not sure if the current ones would all work).

**Comment by datlife** [comment]
Hi @nfelt,

Thank you for asking. 
* Inspired from recent night mode updates of Youtube / Reddit, I think it is okay to keep the images as-is. 
* I am currently using "Dark Mode" Extension on Google Chrome to switch to night mode. However, for Tensorboard, the scalar tab is blacked out whenever I enable the extension.
* Yeah, true that the color palettes might be messed up. I do not have experience in web development so I am not sure how to comment on this.

Thanks.
Dat

**Comment by nfelt** [comment]
Hmm, if you get a chance could you post a screenshot of what Tensorboard looks like with the extension?  Even if it doesn't look quite right.

**Comment by datlife** [comment]
Sure!

Here is the example of before and after I toggle the Dark Mode extension

### Before
![selection_009](https://user-images.githubusercontent.com/13214917/42587912-06998a7a-84f1-11e8-842d-0c2e3dd78719.png)

### After
![selection_008](https://user-images.githubusercontent.com/13214917/42587918-0963e4d0-84f1-11e8-87ee-c53dfad71851.png)

**Comment by vedal** [comment]
Hi :)
Any updates on this feature?

**Comment by mhamilton723** [comment]
+1 on this feature req!

**Comment by stephanwlee** [comment]
I am happy to report that we now have the dark theme of TensorBoard. 

![image](https://user-images.githubusercontent.com/2547313/124030454-0e733b80-d9ab-11eb-9354-819525ebbd4d.png)

![image](https://user-images.githubusercontent.com/2547313/124030498-192dd080-d9ab-11eb-9584-107321d66e73.png)

It should default apply the dark mode based on your browser settings (or your OS settings; we use the media query) or you can manually set to use a specific theme by interesting with the menu here:

![image](https://user-images.githubusercontent.com/2547313/124030601-34004500-d9ab-11eb-96b2-be69501ff6d0.png)

The dark mode implementation definitely is not the best and currently lacks support for the third party plugins so please mind your eyes when switching plugins; You might be blinded!

If you identify any usability issues with scalars, graph, and/or timeseries, please file a new issue so we can triage and fix accordingly. In the meanwhile, we will try to make the theme overrides persisted across TensorBoard.

To use the new dark mode today, please try our tb-nightly. But since we will have 2.6.0 release "soon", you can wait for that, too.

Sorry about the wait and happy TensorBoarding!

**Comment by LvLs9** [comment]
@stephanwlee a bit bad color scheme... But thanks a lot!
