### ISSUE TITLE
No dashboards are active for the current data set.

### ISSUE THREAD

**Issue by ding-hai-tao** [tensorflow/tensorboard#1306]
Consider Stack Overflow for getting support using TensorBoard - they have a larger community with better searchability:

https://stackoverflow.com/questions/tagged/tensorboard

For bug reports, please include the following:

 - TensorBoard version=1.8.0
 - OS Platform and version ( Ubuntu 16.04)
 - Python version (3.6)
 - For browser-related issues:
   - Browser type and version (Chrome 64.0.3282.140)
   - Screenshot if it's a visual issue
 
Please describe the bug as clearly as possible, and if possible provide a minimal example (code, data, and/or command line) to reproduce the issue.  Thanks!

![screenshot from 2018-07-24 22-05-55](https://user-images.githubusercontent.com/33212030/43143653-d470f36a-8f8d-11e8-82c0-0d120b127845.png)

The error shown in the figure appears, how to solve it? Thank you!

**Comment by stephanwlee** [comment]
Hi Ding-Hai-Tao,
Sorry if I am uninformed, but is `=\home\b1906\htding\lanenet-lane-detection-master\tboard\lanenet\vgg` is legal path? Can you `ls` it?

**Comment by nfelt** [comment]
@ding-hai-tao It looks like you have an extra space in `--logdir =\home\...` it should be `--logdir=\home\...` or `--logdir \home\...`.  (either a space, or an equals sign, but not both)

**Comment by yanhongwang** [comment]
Hi @nfelt 

Is that specific **logdir** folder needed to be initialized something?
I have the same error page as showed above.

Thanks.

**Comment by kdx2** [comment]
@garcia-nacho Do user@MyPC:~/Python/runs$ tensorboard --logdir="/home/user/Python/runs/" instead of user@MyPC:~/Python/runs$ tensorboard --logdir /home/user/Python/runs/, what you show on the log. Also make sure that you call Tensorboard outside the folder in which you write the logs, as this invokes EXACTLY the same error message, too. Try and tell me :) :+1:

**Comment by banMei** [comment]
@ding-hai-tao ,maybe  I got an answer.You can try to run your .ipynb file on the terminal. And then, you can navigate the http://localhost:6006.

**Comment by anhduc2203** [comment]
> @garcia-nacho Do `user@MyPC:~/Python/runs$ tensorboard --logdir="/home/user/Python/runs/" ` instead of `user@MyPC:~/Python/runs$ tensorboard --logdir /home/user/Python/runs/`, what you show in the log. Also, make sure that you call Tensorboard outside the folder in which you write the logs, as this invokes EXACTLY the same error message, too. Try and tell me :)

thanks bro

**Comment by tribbloid** [comment]
Also affect me, I'm using pytorch 1.2.0 so not sure if it is the right thread.

```
# %%
import os

import torch
from tensorboard.program import TensorBoard
from torch.utils.tensorboard import SummaryWriter
from torchvision.models import resnet
from torchvision.models._utils import IntermediateLayerGetter
from torchvision.models.detection.backbone_utils import resnet_fpn_backbone

from gate_detection.model.detection._utils import IntermediateLayerTuple
from gate_detection.utils import StrUtil
from gate_detection.utils.testingUtils import It

# %%

write = SummaryWriter()

tbDir = os.path.abspath(write.log_dir) + '/'

print(f"SummaryWriter is writing into {tbDir}")

tb = TensorBoard()
# tb.configure(argv=[None, '--logdir', "'" + tbDir + "'"])
tb.configure(logdir=tbDir)
url = tb.launch()

# %%

net = resnet.resnet34()
print(net)
x = torch.rand(1, 3, 300, 300, dtype=torch.float32)
write.add_graph(net, x, verbose=True)
write.flush()
```

**Comment by nfelt** [comment]
I'm closing out this issue since "No dashboards are active" is the standard message if TensorBoard can't find your data, and it's not a bug in TensorBoard unless you can show why TensorBoard should be finding your data.

If you believe you're seeing the error because of a bug in TensorBoard, please open a new issue and fill out enough detail to be clear on how to easily reproduce the problem.

@tribbloid can you confirm first that the problem is not on the PyTorch side, since you're using the PyTorch-provided SummaryWriter, and if so, open a new issue for this with the full issue template details?  It would also help if you can attach the specific event files in the logdir you're using that you expected TensorBoard to be displaying.

**Comment by tribbloid** [comment]
no problem, here you go.

**Comment by nan-hub** [comment]
> @garcia-nacho Do `user@MyPC:~/Python/runs$ tensorboard --logdir="/home/user/Python/runs/" ` instead of `user@MyPC:~/Python/runs$ tensorboard --logdir /home/user/Python/runs/`, what you show in the log. Also, make sure that you call Tensorboard outside the folder in which you write the logs, as this invokes EXACTLY the same error message, too. Try and tell me :) 👍

work for me!
