### ISSUE TITLE
Fails silently if port is occupied

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorboard#1320]
TensorBoard 1.9.0 fails silently if port is already occupied

```
tensorboard --logdir /tmp/hi --port 6006
TensorBoard 1.9.0 at http://mac.lan:6006 (Press CTRL+C to quit)
```
Downgrading to version 1.8 fixes this

```
base) ÷18-07-27 09:34:02|ttys012|mac|~\÷ tensorboard --logdir /tmp/hi --port 6006
E0727 09:34:20.147497 MainThread main.py:197] TensorBoard attempted to bind to port 6006, but it was already in use
TensorBoard attempted to bind to port 6006, but it was already in use
```

**Comment by nfelt** [comment]
Ok, I finally got to the bottom of this issue, which I will send a PR to fix.  For posterity:

Th IPv4/v6 handling logic first attempts to bind to an empty host, and then assumes any error was due to a lack of IPv4, and would then fall back to an explicit IPv6 wildcard (`::`).  There are a number of problems with this approach:

1) Passing in a blank host is unreliable.  Python's socket module says the following:

    > For IPv4 addresses, two special forms are accepted instead of a host address: the empty string represents INADDR_ANY, and the string '<broadcast>' represents INADDR_BROADCAST.

    This is true of socket.bind(), which Werkzeug used to call directly, resulting in TensorBoard binding to the IPv4 wildcard address.  However, in the past year https://github.com/pallets/werkzeug/pull/1150 changed this logic to pass the host and port through a call to getaddrinfo() first, and `getaddrinfo('')` exhibits inconsistent behavior depending on the platform:

    - On Debian, the empty string raises an error (which leads Werkzeug to do what it used to, pass the empty string to bind, and results in a wildcard bind as expected)
    - On macOS, the empty string makes getaddrinfo() return only the loopback/local IPs
    - On Windows, the empty string makes getaddrinfo() return [all registered addresses](https://docs.microsoft.com/en-us/windows/desktop/api/ws2tcpip/nf-ws2tcpip-getaddrinfo#remarks)

2) Errors from the empty-host bind weren't necessarily IPv4 failures - sometimes they were "address in use" errors, which the handling logic expects later, but not until after trying the fallback bind().

3) When binding to the IPv6 wildcard address in the fallback, whether this conflicts with an IPv4 wilcard binding depends on the platform again - specifically whether IPv4-mapped IPv6 addresses are enabled by default or not.  When they are enabled, the IPv6 wildcard `::` will "map" to the IPv4 wildcard `0.0.0.0`, so attempting to bind to `0.0.0.0` after `::` is occupied will fail (note that the reverse, binding to `::` after `0.0.0.0`, seems also platform-dependent - it succeeds on macOS and fails on Debian).  IPv4-mapped IPv6 addresses are enabled by default on my Debian machine, but disabled on macOS, although individual sockets can set IPV6_V6ONLY=0 to re-enable the behavior.

The combination of these three defects produces this issue, where only on macOS, binding a second TensorBoard instance to the same port will succeed unexpectedly, because the first time the second TensorBoard calls bind() it fails with "address in use" and incorrectly falls back to IPv6 `::` (issue 2 above), and this doesn't conflict with the IPv4 binding of the first TensorBoard instance because IPv4 mapping is disabled (issue 3 above).  Even when those issues are fixed, the blank host is still a problem (issue 1 above) because the Werkzeug change makes TensorBoard bind to 127.0.0.1 on macOS instead of the wildcard, and that *still* causes the "silent success" problem on fallback, since the macOS socket implementation, unlike Linux, [interprets SO_REUSEADDR to allow a wildcard binding to "overlap" with a specific binding](https://stackoverflow.com/a/14388707/1179226).
