### ISSUE TITLE
there is always a module named report_uninitialized_variables in tensorboard

### ISSUE THREAD

**Issue by chenbohua3** [tensorflow/tensorboard#1328]
- TensorBoard version : 1.8
 - TensorFlow version : 1.8
 - OS Platform and version :Linux Ubuntu 16.04
 - Python version 3.6

whenever I train a module with estimator, a module named report_uninitialized_variables_1 always occurred in the graph in tensorboard.

Do anyone know what it means, does it mean that the variables in the graph are uninitialized even if I specified the way to initialize

**Comment by nfelt** [comment]
This is an Op that Estimator automatically adds the the graph.  I don't think it indicates any issue with your model; Estimator just always adds that op so that if there are uninitialized variables they'll be handled appropriately.

If you want to know more, asking on TensorFlow stackoverflow might be your best bet - this isn't anything specific to TensorBoard which I'm pretty sure is just reflecting the actual graph produced by Estimator.

**Comment by chenbohua3** [comment]
thank you @nfelt ~
