### ISSUE TITLE
Smoothed curve way off the actual line

### ISSUE THREAD

**Issue by danijar** [tensorflow/tensorboard#1439]
Without smoothing:
![screenshot](https://user-images.githubusercontent.com/2111293/45771414-093a0d00-bc13-11e8-8840-d7e113803e38.png)
Smoothing 0.9:
![screenshot](https://user-images.githubusercontent.com/2111293/45771393-fc1d1e00-bc12-11e8-9ba6-62dd293f3d4d.png)
I don't see any reason why the smoothed curve should be so far away from the actual data.

**Comment by TheGuywithTheHat** [comment]
I think this is because the current algorithm essentially sets each smoothed point to the weighted average of all original data points that come _before_ it in the series. Relevant code here: https://github.com/tensorflow/tensorboard/blob/cbfa27d2b3277adaf8dada16b2856527a830c7bc/tensorboard/components/vz_line_chart/vz-line-chart.ts#L1029-L1064

Current policy on the smoothing algorithm, from https://github.com/tensorflow/tensorboard/issues/610#issuecomment-334380578:

> It seems that every change in the smoothing algorithm results in new tradeoffs and biases, and new requests to change the algorithm. At this point it's not a priority for the team, so just filing an issue probably won't directly result in changes. However, the smoothing algorithm is actually a very simple piece of code to change. If you come up with a new algorithm, and demonstrate persuasively why it is an improvement over the current one (taking into account new biases and edge cases that it introduces), I'll happily merge it.

**Comment by gowtham-kp** [comment]
Closing the issue due to lack of recent activity. Please add additional comments and we can reopen the issue again. Thanks!
