### ISSUE TITLE
logDir has default path?when I set tf.summary.FileWriter(tensorboard_dir) but not validate

### ISSUE THREAD

**Issue by OliveZT** [tensorflow/tensorboard#1442]
1. Setting the save_dir: /checkpoints/textcnn
`save_dir = os.path.join(run_path, 'checkpoints/textcnn')
save_path = os.path.join(save_dir, 'best_validation')`

2. Setting the FileWriter path: /tensorboard/textcnn
tensorboard_dir = 'tensorboard/textcnn'`
tf.summary.FileWriter(tensorboard_dir)`

3. Running the tensorboard: 
`MacBook-Pro:tensorboard xintin$ tensorboard --logdir=textcnn` 

4. Visiting 127.0.0.1:6006

5. Navigating to 'Scalars' tab shows "NO scalar data was found"

6. Looking for the log directory path at the bottom of the left sidebar, shows the log dir:
`/checkpoints/textcnn`

7. Soooooooo Why?

**Comment by nfelt** [comment]
Closing since this doesn't sound like a bug in TensorBoard, but feel free to reopen if you think it's a bug and you can clarify exactly what behavior you are expecting and what TensorBoard is doing differently.

TensorBoard resolves a relative logdir path against the current directory.  So if you are in a directory called "/checkpoints" then running `tensorboard --logdir=textcnn` will load data from the directory `/checkpoints/textcnn`.  If you want TensorBoard to load data from a different directory like `/tensorboard/textcnn` you'll need to pass that as an absolute path, like `tensorboard --logdir=/tensorboard/textcnn`.
