### ISSUE TITLE
Logfile size higher than necessary?

### ISSUE THREAD

**Issue by srossi93** [tensorflow/tensorboard#1539]
Hi, 

I was trying to parse/work with Tensorboard logfiles and I noticed some weird behaviours regarding their size.

Let's take this example (but I think it's quite easily to reproduce similar setup). 

``` bash
> du -h events.out.tfevents.1539877071.notebook-gpu0-455-prod
195M    events.out.tfevents.1539877071.notebook-gpu0-455-prod
```
This file stores only scalars (no histograms, no images, no distributions) in 7 tags for 1M iterations at different intervals, for a total of roughly 4M events. 
Seems that each event (that I assume is stored compressed somehow - is it?) takes more than 48 B. As far as I understood, each scalar event is made of 3 fields (value, wall time and steps) plus additional data. Even assuming 64bits/8B per field of non-compressed data, more than half of the space (> 24B) is allocated (wasted?) for something else. 

Moreover, I can see huge improvements if I parse and save all the data in different formats. For instance: 

```python 
import numpy as np
from tensorboard.backend.event_processing.event_accumulator import EventAccumulator
event_acc = EventAccumulator('.')
event_acc.Reload()     # This takes up to 10 minutes on my machine (single threaded?)

for tag in event_acc.Tags()['scalars']:
    raw_data = np.array(event_acc.Scalars(tag))
    np.save(tag.replace('/', '_') + '.npy', raw_data)
    np.savetxt(tag.replace('/', '_') + '.csv', raw_data)
```

``` bash
> find . -type f -name '*.csv' -exec du -ch {} +
76K     ./error_test.csv
76K     ./model_lr.csv
736K    ./model_dkl.csv
736K    ./loss_train_nll.csv
736K    ./loss_train.csv
736K    ./error_train.csv
76K     ./loss_test.csv
3.1M    total

> find . -type f -name '*.npy' -exec du -ch {} +
236K    ./model_dkl.npy
24K     ./error_test.npy
24K     ./loss_test.npy
236K    ./loss_train_nll.npy
236K    ./error_train.npy
24K     ./model_lr.npy
236K    ./loss_train.npy
1016K   total
```
So, the question is: why are Tensorboard logfiles this big? 
Is it meant to be like this? Are logfiles compressed or just a binary dump? 

Setup:
``` bash
> pip3 show tensorboard tensorflow
Name: tensorboard
Version: 1.11.0
Summary: TensorBoard lets you watch Tensors Flow
Home-page: https://github.com/tensorflow/tensorboard
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /home/user/anaconda3/lib/python3.6/site-packages
Requires: numpy, six, markdown, werkzeug, wheel, protobuf, grpcio
Required-by: tensorflow
---
Name: tensorflow
Version: 1.11.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /home/user/anaconda3/lib/python3.6/site-packages
Requires: six, setuptools, tensorboard, termcolor, keras-applications, astor, absl-py, protobuf, gast, wheel, numpy, keras-preprocessing, grpcio
Required-by:
```

**Comment by nfelt** [comment]
Each scalar event also stores the tag as a string.  How long are your tag lengths?  Those could pretty easily account for an extra 20-30 bytes depending on tag length.  There's also CRCs at the record level built into the surrounding container format which would add 8 bytes per record: https://github.com/tensorflow/tensorflow/blob/cf42142de6046089d62363590863d36ef0046b13/tensorflow/core/lib/io/record_writer.cc#L96-L100  And yes, the format is not compressed at all, and it's definitely not space-optimal for the data being stored.

We have medium-term plans to improve this, but for now, your best bet would be using shorter tag names (if that's indeed where the overhead is coming from) and potentially combining many scalar summaries values (tf.Summary.Value) into a single tf.Event, which would spread the CRC overhead across more actual scalars.

The event file should compress the tags relatively well since I believe they're stored essentially as the raw bytes, but I don't believe TensorBoard currently has the logic to read compressed event files, so it would still need to be decompressed prior to reading.
