### ISSUE TITLE
Scalar word break is ugly.

### ISSUE THREAD

**Issue by dgrahn** [tensorflow/tensorboard#1549]
This is what the scalar plugin looks like for me when the hyper parameter line is too long.

![image](https://user-images.githubusercontent.com/394709/47513049-744ab500-d84b-11e8-8bcc-29ff7e4c435d.png)

I recommend changing the word-break to `break-all`. It then looks like this.

![image](https://user-images.githubusercontent.com/394709/47513276-e4593b00-d84b-11e8-9ffe-20a01a635d96.png)

If this sounds good, I'll make a PR.

**Comment by stephanwlee** [comment]
@nfelt what do you think about break-all? I forgot exactly why we prefer #628 over break-all... 🤔

**Comment by nfelt** [comment]
So the goal of the abandoned #628 was to break at a wider set of punctuation characters (specifically `\/=\-_,`).  This is a middle ground between the current version (which breaks only at the default spots, so in the case above, only on hyphens) and `break-all` which breaks everywhere.

I still think that would be ideal since it avoids making breaks needlessly in the middle of actual words (see screenshots on #628 for an example).  But I'll grant that `break-all` is still better than the default behavior so I'm fine approving #1602.

**Comment by stephanwlee** [comment]
#1602 is merged so will close the issue. Thanks!
