### ISSUE TITLE
[feature-request] What-if Tool demos for text data?

### ISSUE THREAD

**Issue by hsm207** [tensorflow/tensorboard#1736]
Is there an example of using the What-if Tool to probe models that use text data as input e.g. text classification? I couldn't find any in the demos section in the What-if Tool [website](https://pair-code.github.io/what-if-tool/index.html#demos).

**Comment by jameswex** [comment]
There are no public-facing demos of using WIT to probe models that have text as input, but it does work. For text classification, you can have a feature in your dataset that is the text to classify and the feature contains on feature value per example where the feature value is the string of text to classify (a word, sentence, paragraph, whatever). Then train a classification model on that dataset and view it in WIT.

Currently WIT doesn't do a great job of displaying long string feature values (the text gets cut off and you need to move the cursor along to view the entire text), but the tool does work correctly.  You can change the text of an example and then click the "run inference" button to see what a change in the words has on the classification.

Do you have a trained TF model that does text classification from a dataset of tf.Example protos, where the text is an input feature of the example? If so, the tool should work as expected. Let me know if you are seeing otherwise.
