### ISSUE TITLE
Which kind of trained models can I use?

### ISSUE THREAD

**Issue by statgirl101** [tensorflow/tensorboard#1746]
Hi There,
I am new to using the what-if tool. I would like to use it to see if my ML model is fair or not; I already have a trained XGBoost model (booster object, saved model). How can I use this model with the what-if tool and is this even possible? I notice in your code that can be modified by users the WIT-from scratch.ipynb that you use classifier = tf.estimator.LinearClassifier
What if I already have a saved model that is of the form I mentioned above (xgboost)? Can I still use the what-if tool or not. I am concerned that tensorflow does not support these types of booster object type models. Any help would be appreciated!!!! Thanks!

**Comment by jameswex** [comment]
Right now, as per documentation here (https://github.com/tensorflow/tensorboard/tree/master/tensorboard/plugins/interactive_inference), WIT supports tensorflow estimator classification or regression models that use the tensorflow-serving Predict, Classify or Regress APIs and take tf.Example protos as input. It doesn't support other model types at this point.

In the future I hope to allow users with models such as yours to be able to use the tool by writing a simple wrapper for your model and data so that it is compatible with the tool.
