### ISSUE TITLE
Create a chart inside the tooltip

### ISSUE THREAD

**Issue by amirmog** [tensorflow/tensorboard#1751]
Could someone please help understand how I can extend the pr curves plugin so that it would be possible to plot a chart/graph inside the tooltip?

Any tip or pointers would be much appreciated,

Best,
Amir

**Comment by manivaradarajan** [comment]
Amir, thanks for your problem report.

Unfortunately, this is not something that is easy to do in the current framework. Parts of the tooltip are drawn with d3 and it's non-trivial to get Polymer to interact correctly with the tooltip because it has to "pop out" of the DOM.

Could you give a description of what problem you're trying to solve in doing this? Perhaps we can come up with alternate solutions.

**Comment by hgadig** [comment]
Closing as this issue is inactive and in "awaiting response" state for long time. Feel free to add your comments and we will reopen. Thanks!
