### ISSUE TITLE
tensorboard cpu problem

### ISSUE THREAD

**Issue by hyunseunghee** [tensorflow/tensorboard#1865]
Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
tf.Tensor(546.6641, shape=(), dtype=float32)

**Comment by wchargin** [comment]
Hi @hyunseunghee! Thanks for the report.

This is a warning due to TensorFlow, not TensorBoard. It doesn’t mean
that anything is _wrong_; it does mean that TensorFlow could be running
faster. When you install TensorFlow via pip, it downloads pre-built
binaries that should work for most people’s CPUs, but your CPU supports
additional instructions that would let TensorFlow run even faster. To
take advantage of these instructions, you’ll want to build TensorFlow
from source.

You can read more about this message here:
<https://stackoverflow.com/q/47068709>

You can read about how to build TensorFlow from source here:

  - for Linux or macOS: <https://www.tensorflow.org/install/source>
  - for Windows: <https://www.tensorflow.org/install/source_windows>

Finally, if you want to use a GPU, please install the `tensorflow-gpu`
package instead.
