### ISSUE TITLE
%tensorboard magic doesn't work on docker

### ISSUE THREAD

**Issue by frogermcs** [tensorflow/tensorboard#1947]
When I try to launch `%tensorboard` magic in jupyter notebook on docker, it results with a screen telling "localhost refused to connect."

**Details**
Docker run:
```
$ docker run -p 8888:8888 -v $(PWD):/tf/notebooks -it tensorflow/tensorflow:nightly-py3-jupyter
```

In jupyter notebook I do everything like described [here](https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/r2/get_started.ipynb):

```
# Load the TensorBoard notebook extension
%load_ext tensorboard.notebook
%tensorboard --logdir output/training_summaries
```

Which ends up with mentioned refused connection.

If I define port and host like here:
```
%tensorboard --logdir output/training_summaries --host 127.0.0.1 --port 8888
```

It ends up with:
```
ERROR: Failed to launch TensorBoard (exited with 255).
Contents of stderr:
E0302 18:53:49.648446 140082989455104 program.py:232] TensorBoard could not bind to port 8888, it was already in use
ERROR: TensorBoard could not bind to port 8888, it was already in use
```

**Comment by hgadig** [comment]
This could be probably due to firewall restrictions. Could you try in [Colab](https://colab.sandbox.google.com/) and check if you face the same issue ?

**Comment by wchargin** [comment]
Hi @frogermcs! Thanks for the report.

What’s happening in your first command is that you’re opening the
Jupyter notebook in your normal web browser, outside the container. When
your Jupyter notebook attempts to connect to localhost:6006, it tries
your actual machine’s port 6006 rather than port 6006 within the
container. Hence, the connection is refused, unless you also have a
TensorBoard running _outside_ the container, in which case that
TensorBoard will be displayed.

In your second example, you’re trying to bind TensorBoard to port 8888,
but that’s the port used by the Jupyter runtime itself, which is why it
appears as in use (it is).

You’ll need to forward the appropriate ports from your Docker container
to the host. For instance, consider invoking Docker like this:

```shell
sudo docker run -p 8888:8888 -p 6006-6015:6006-6015 \
  -v "${PWD}:/tf/notebooks" -it tensorflow/tensorflow:nightly-py3-jupyter
```

This will allocate enough ports for you to have 10 concurrent
TensorBoard instances within your container, which should probably be
enough. Adjust to taste, of course.

Then you can just use `%tensorboard` without manually specifying a host
or port:

![tb_docker](https://user-images.githubusercontent.com/4317806/53754318-73183d00-3e68-11e9-9b7b-0d30ab285c91.png)

**Comment by nfelt** [comment]
@wchargin maybe it's worth adding a note about the docker use case to the tensorboard-in-notebooks docs somewhere?

**Comment by wchargin** [comment]
@nfelt: Agreed; opened #1952.
