### ISSUE TITLE
Tensorboard not detecting Graph definiton files

### ISSUE THREAD

**Issue by ShaVikas** [tensorflow/tensorboard#1949]
Tensorboard not displaying Graph and showing message "No graph definition files were found."

```
import tensorflow as tf
tf.Variable(42, name='foo')
w = tf.summary.FileWriter('./testdir')
w.add_graph(tf.get_default_graph())
w.flush()
w.close()
```
Tried below:
```
tensorboard --logdir='D:\Users\XXXXX\jupyterNotebooks\tensorflow\testdir'
tensorboard --logdir 'D:\Users\XXXXX\jupyterNotebooks\tensorflow\testdir'
tensorboard --logdir='.\testdir'
tensorboard --logdir '.\testdir'
```

- Verified file is created at given path and file is not blank.
- Tried on chrome and firefox and internet explorer
- Scalars screen show the right path

S/w Version info:
 - TensorBoard version          1.12.2
 - TensorFlow version            1.12.0
 - OS Platform and version    Windows 10 Version 1511 (OS Build 10586.1717)
 - Python version                   Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
 - Browser version                 Chrome Version 72.0.3626.119 (Official Build) (64-bit)

**Comment by hgadig** [comment]
Can you try removing quotes when you give absolute path and see if you are still running into the issue ?

**Comment by wchargin** [comment]
Hi @ShaVikas! Thanks for the report. I suspect that using double quotes
instead of single quotes will resolve your issue. In a Windows shell,
single quotes will be passed through literally to the program, so by
writing `--logdir '.\testdir'` you’re asking TensorBoard to look for a
directory called `testdir'` inside a directory called `'.`, which is not
what you mean.

Could you please try either `tensorboard --logdir .\testdir` or
`tensorboard --logdir ".\testdir"` and let us know whether these work?

**Comment by ShaVikas** [comment]
Thanks a lot, using double quotes fixed the issue
