### ISSUE TITLE
%tensorboard magic: host other than localhost

### ISSUE THREAD

**Issue by wookayin** [tensorflow/tensorboard#1956]
For bug reports, please include the following:

 - TensorBoard version (from pip package, also printed out when running `tensorboard`) : 1.13.0
 - OS Platform and version (e.g., Linux Ubuntu 16.04) : Linux, but applies to ALL distributions
 - Python version (e.g. 2.7, 3.5) : 3.6
 
The recently introduced `%tensorboard` magic is really cool! But it has some certain limitations: the iframe host is set to be `localhost` only. In many cases where one is running juypter/tensorboard in a remote server, this won't be simply working. Of course, the iframe will say `connection refused`.

See this line 
https://github.com/tensorflow/tensorboard/blob/master/tensorboard/notebook.py#L360 :  the hostname is hard-coded.

An easy fix to this would be: make host be configurable (as a parameter) and have the `--host` parameter, for example, from the `%tensorboard` magic propagated. What do you think about this change? It would be an easy fix, so once we reach to an agreement I could submit a patch.

**Comment by wchargin** [comment]
Yes, the host is fixed. We discussed this as part of the original
design, and didn’t assign it a high priority because the initial goal
was to have solid support for TensorBoard in Colab—in Colab, a service
worker proxy forwards requests to `https://localhost:*/` to the actual
backing VM, hence this design.

TensorBoard already accepts a `--host` command-line argument, which
controls the interfaces to which the server will attempt to bind.
(Namely: it has _different_ semantics from what you seem to want.)
Furthermore, reading an argument value to determine how to render
TensorBoard in the UI is not actually an easy patch: the arguments
provided by the user are merely lexed by the notebook extension; only
the underlying tensorboard(1) binary actually parses them. Probably the
right thing to do _if_ you wanted to add a new flag would be to thread
the information through the TensorBoard info file, but I don’t think
that adding a new flag is the way to go.

If we wanted to add support for this, my initial thoughts would be as
follows. We should change `tensorboard.notebook.display` to accept
kwargs `host` and `protocol` that control the origin of the iframe,
defaulting to `"localhost"` and `"http"`, respectively. To facilitate
the simpler `%tensorboard` magic interface, we could let these
parameters have default values taken from module globals set by a new
function `tensorboard.notebook.configure`. Then a typical session might
look like:

```python
%load_ext tensorboard.notebook

from tensorboard import notebook
notebook.configure(host="wookayin-tensorboard.appspot.com")

%tensorboard --logdir ./logs  # automatically uses the right host
```

Let’s talk more before you submit a patch. (cc @nfelt for design
feedback)

**Comment by nfelt** [comment]
I agree with the `display()` change, though it might be simpler to just allow `host` to include the scheme and parse it out if provided.

Re: the default value, even though `--host` is semantically not the exact same thing, in practice when used it will often be the same, and it seems reasonable enough that it could be used as the default value when provided.  We can just log it in the TensorBoardInfo, and when calling `display()` directly or via the magic, if there's no `host` argument, then we try the `--host` value (probably printing a message about it so it's clear what happened if it fails).  In the Colab case we can just always use `https://localhost` (and error out if the user called `display(host=notlocalhost)` since nothing else will work.

Yes, this default won't work for notebook users who need to bind to a particular hostname to serve but can't have the iframe connect to the same hostname (e.g. it's behind some internal firewall).  I think that use case is pretty small and this default isn't worse than localhost in virtually all such cases.

The only remaining case I could see is where you want to run a local tensorboard that's available publicly using an explicit `--host 0.0.0.0` (currently there's little reason to do that since it's the default, though I think we may someday want to change that to improve our default security story).  If we get a `--host 0.0.0.0` then since that address is useless for remote connections, we could instead resolve a name or IP address for the machine and store that instead (or in an auxiliary TensorBoardInfo field).

Personally, I'd prefer that over introducing global configuration state.

**Comment by tlkh** [comment]
Just one to add in one common scenario that would require the user to specify a hostname (to view TensorBoard) that is **different** from the `--host` parameter that is passed to `tensorboard`.

On shared GPU servers (e.g. university) it is very common for users to be required to run jobs in a Docker container for isolation. In this case, TensorBoard is running within the container and host parameter is `0.0.0.0`, and the port is exposed through some other mechanism. However, to view TensorBoard you will need to connect to the hostname (e.g. IP address) of the GPU server (e.g. `10.1.2.3`).

Also similar is if you are also using TensorBoard in Docker on any other remote server. `host` will be `0.0.0.0` to allow for port-forwarding out of the container, and actual hostname to connect to will be the public IP address of the server.

In both scenario, there should be the flexibility of allowing the user to pass an additional argument into `display()` like following:

```
from tensorboard import notebook
notebook.display(port=6006, height=1000, hostname="10.1.2.3")
``` 

(non-magic way of accessing TensorBoard referenced from: https://github.com/tensorflow/tensorboard/blob/master/docs/r2/tensorboard_in_notebooks.ipynb)

**Comment by cliffwoolley** [comment]
At NVIDIA, we deliver TensorBoard as well as Jupyter in our NGC containers, and it came up today that we have the problem described in this issue as well when combining the two.  Unfortunately, from inside the container, we won't be able to know what the host's IP address is, so while the default `%tensorboard` magic parameter for `--host=0.0.0.0` works fine for us, the browser (which may be running on a machine completely different than localhost) won't be able to contact the container.  Fortunately, the client does know which hostname to contact, as long as it assumes it's the same one the Jupyter notebook was running from in the first place, just with a different port.  So for our use case, I patched it as in https://github.com/tensorflow/tensorboard/pull/2407 .
/cc @cvinson830
