### ISSUE TITLE
Performance degradation for scalar pane caused by forced reflows in Plottable.js

### ISSUE THREAD

**Issue by jekbradbury** [tensorflow/tensorboard#198]
If I have a few dozen runs visible in the Scalars pane and one or more plots are maximized, Chromium (`Version 58.0.3029.110 Built on Ubuntu , running on Ubuntu 14.04 (64-bit)`) slows to a crawl within a few minutes after a refresh; developer tools points to `plottable.js:14262` (which finds some kind of bounding box, perhaps related to the legend tooltip) as causing a "forced reflow." Since that executes 20x per frame and can take up to 250ms, I'm consistently seeing a frame rate of ~0.2fps.
If I replace
```
try {
    bbox = element.node().getBBox();
}
catch (err) {
    bbox = {
        x: 0,
        y: 0,
        width: 0,
        height: 0
    };
}
return bbox;
```
with
```
return {x: 0, y:0, width:0, height:0};
```
the only difference I can perceive is that everything is faster (but presumably there's something broken behind the scenes).

**Comment by wchargin** [comment]
To confirm, are these the steps to reproduce?
 1. Launch TensorBoard and open categories so that a few dozen scalar
    charts are displayed. (Say, 33 of them.)
 2. Disable auto-reload.
 3. Wait five minutes.
 4. Mouse over tooltips, and observe a frame rate of worse than 1fps.

That's pretty awful if so: I'm in step (3) of your repro now and will
let you know if I observe (4). I don't see anything terrible yet:
![Screenshot of current state](https://user-images.githubusercontent.com/4317806/27979462-1efe4ff8-632b-11e7-81b9-d502413c0f8f.png)


Some questions:
  * You say that "developer tools points to plottable"—are these console
    errors or were you using the Performance panel's profiler? (If the
    latter, over what time interval did you profile?)
  * Does the performance get worse over time, as if something were
    accumulating, or does it suddenly jump to ~0.2fps after "a few
    minutes"?
  * Do you have a stack trace for the Plottable call? If it's an issue
    in Plottable, we may work around it even if we don't fix it, so the
    stack trace would be useful there.

Thanks!

cc @dandelionmane re: Plottable

**Comment by wchargin** [comment]
(amendment: I forgot to maximize some charts. restarting my timer :-) )

![image](https://user-images.githubusercontent.com/4317806/27979530-9334dba8-632b-11e7-92f9-e32a8ab5d772.png)

**Comment by jekbradbury** [comment]
Sorry, I mean several dozen runs but only a handful of plots. Here are some screenshots:
![tb1](https://user-images.githubusercontent.com/11729078/27979648-54753c04-632c-11e7-8809-8e8fb2ac242c.png)
![tb2](https://user-images.githubusercontent.com/11729078/27979649-5484590a-632c-11e7-9356-f2291245ae66.png)
And it gets worse over time rather than all at once.

Perhaps I'm only seeing an issue because I'm using the TensorBoard backend through https://github.com/torrvision/crayon? As far as I know, that doesn't modify the frontend at all though...

**Comment by jekbradbury** [comment]
Bottom-up call stack:
![tb3](https://user-images.githubusercontent.com/11729078/27979742-2c3c3b1a-632d-11e7-84fd-ee8b13202b91.png)

**Comment by wchargin** [comment]
Thanks a bunch.

Hmm. After ten minutes of letting it idle, then interacting with the charts by hovering around them (to change the tooltip values) and dragging them to zoom in and out, I'm experiencing non-terrible frame rates—around the 10–20 FPS range. I do see the forced reflows, but they take on the order of 0.69 ms each rather than your 250 ms:

![image](https://user-images.githubusercontent.com/4317806/27979794-794573f4-632d-11e7-97d6-3fc77c4fd58f.png)

I do note that your TensorBoard is significantly older than mine; we haven't have "Split on underscores" as an option for a few months. I wonder to what extent this affects the issue.

Your call stack seems to indicate that this happens when setting the series data for the chart, which only happens upon data reload. In the version of TensorBoard that you're running, this will also happen if you toggle the set of active runs a bunch (it was accidentally quadratic; I fixed this in #163). Is this something that you're doing? (If so, upgrading your TensorBoard will likely help a lot.)

When I do force a reload, the closest call stacks that I can see to yours (large proportion of total time, involving `setSeriesData`) seem to bottleneck in `map`-native code and `_computeExtent`, which is a pure-JS function:
```js
c.prototype._computeExtent = function(a, b, c) {
    var d = b.accessor;
    b = b.scale;
    if (null == b)
        return [];
    var e = a.data();
    null != c && (e = e.filter(function(b, d) {
        return c(b, d, a)
    }));
    e = e.map(function(b, c) {
        return d(b, c, a)
    });
    return b.extentOfValues(e)
}
c.prototype.extentOfValues = function(a) {
    a = f.extent(a.filter(function(a) {
        return k.Math.isValidNumber(+a)
    }));
    return null == a[0] || null == a[1] ? [] : a
}
```

Any thoughts?

**Comment by jekbradbury** [comment]
I'll rebuild the docker image I'm using (didn't realize https://hub.docker.com/r/alband/crayon/ hadn't been pushed in 5 months) and I imagine that'll at least make things better.
I can't get over how incredibly responsive you all are...thanks so much for your help!

**Comment by jekbradbury** [comment]
Confirmed that the build with up-to-date TensorBoard doesn't have this problem for me. Sorry for the noise.

**Comment by wchargin** [comment]
Great—thanks for confirming! No apology necessary; please come again. :-)
