### ISSUE TITLE
Support for HTML-based word annotations in tf.summary.text

### ISSUE THREAD

**Issue by Abhijit-2592** [tensorflow/tensorboard#2046]
Since tf.summary.text supports markdowns, It will be great if it supports HTML too. Because, IT becomes easier to visualize NER, POS tagging training easier. For example, 
```
<div class="entities" style="line-height: 2.5">But \n<mark class="entity" style="background: #7aecec; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; b
order-radius: 0.35em; box-decoration-break: clone; -webkit-box-decoration-break: clone">\n    Google\n    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem">ORG</span>\n</mark>\n is starting from behind. The company made a late push. But \n<mark class="entity" style="background: #7aecec; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em; box-decoration-break: clone; -webkit-box-decoration-break: clone">\n    Apple\n    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem">ORG</span>\n</mark>\n\'s \n<mark class="entity" style="background: #bfeeb7; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em; box-decoration-break: clone; -webkit-box-decoration-break: clone">\n    Siri\n    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem">PRODUCT</span>\n</mark>\n is available on iPhones</div>
```
Visualizing the above HTML will be more appealing while training an NER model. Now I guess the only way to visualize an NER training is to view them as 2D tensors with one column being the tag name and the other column being the text

**Comment by nfelt** [comment]
Thanks for the feature request.  I think we're unlikely to want to expose anything other than a small subset of HTML for security reasons, since that would increase the risk of XSS - I've narrowed the issue title accordingly.

This seems fairly related to feature request https://github.com/tensorflow/tensorboard/issues/1740 which is for a way to indicate attention via highlighting.  I realize the exact use case here is different, but they're both about ways to annotate text to indicate extra information.  Perhaps there's a limited set of HTML or some kind of markdown extension that would allow for basic text annotation without making it too hard to safely sanitize the result.  If you agree it's similar, mind if I consolidate the issues?

In any case, while I think we'd welcome contributions along those lines, I'm not sure when we would get to implementing this functionality ourselves.

**Comment by Abhijit-2592** [comment]
@nfelt  Sure we can merge the issues if you feel it's better that way. Meanwhile will check if there are any markdown extension alternatives

**Comment by nfelt** [comment]
Duplicate of #1740

**Comment by nfelt** [comment]
Okay, I'll centralize on #1740 - feel free to chime in there if you find anything.
