### ISSUE TITLE
Plugin Projector Visualize Embeddings: 'ResourceSummaryWriter' object has no attribute 'get_logdir' 

### ISSUE THREAD

**Issue by alew3** [tensorflow/tensorboard#2098]
Tensorboard: tb-nightly==1.14.0a20190319
Tensorflow: tf-nightly-gpu-2.0-preview==2.0.0.dev20190403
Ubuntu 18.04

it is calling a method that doesn't exist 

/tensorboard/plugins/projector/__init__.py in visualize_embeddings(summary_writer, config)
     50     ValueError: If the summary writer does not have a `logdir`.
     51   """
---> 52   logdir = summary_writer.get_logdir()
     53 
     54   # Sanity checks.

AttributeError: 'ResourceSummaryWriter' object has no attribute 'get_logdir'

**Comment by albertbuchard** [comment]
What was the problem with this please ? I have a similar error..

**Comment by psybuzz** [comment]
Hi, thanks for letting us know.  Could you please file a new issue or elaborate on what the error is?  It would be helpful for us to investigate an issue with what is expected / repro steps.

Also, a change to the projector plugin ~2 months ago (https://github.com/tensorflow/tensorboard/pull/2665), landed in `tensorboard==2.0.1` and `tb-nightly`.  If the issue is projector related, could you let us know if upgrading to one of those packages fixes it?
