### ISSUE TITLE
UsageError: Line magic function `%tensorboard` not found.

### ISSUE THREAD

**Issue by podlipensky** [tensorflow/tensorboard#2226]
- TensorBoard version: the one in tf-nightly
 - TensorFlow version: tf-nightly
 - OS Platform and version (e.g., Linux Ubuntu 16.04), CPU
 - Python version 3.6

Can't use tensorboard in colab with python3: https://colab.research.google.com/drive/1RG61ME3VCrqHazqpfrTQSvdX-Hm4G2mR?authuser=1

Removing default tensorboard and tensorflow doesn't help. Note this is an issue with python3 only, python2 works fine.

**Comment by stephanwlee** [comment]
@podlipensky your colab is ACL protected. :\

**Comment by wchargin** [comment]
Your install sequence in that notebook is:

  - By default, `tensorflow` and `tensorboard` are installed.
  - Install `tf-nightly`, which installs `tb-nightly` (now bad state)
  - Remove `tensorflow` and `tensorboard`.
  - Attempt to install `tf-nightly`, which does nothing because the
    package is already installed.

You must uninstall `tensorflow` and `tensorboard` _before_ installing
`tf-nightly`. If you at any point have both nightly and stable installed
at once, then you must remove _both_ and reinstall just the one that you
want.

**Comment by gowtham-kp** [comment]
@podlipensky Dis that answer your question. Can i close the issue?

**Comment by gowtham-kp** [comment]
@podlipensky  Closing this issue due to lack of recent activity. Please add additional comments and we can open the issue again. Thanks!

**Comment by mmehedin** [comment]
> * tf-nightly

after pip uninstall tensorflow   
and pip uninstall tensorboard

pip install -q tf-nightly

ERROR: Cannot uninstall 'wrapt'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
