### ISSUE TITLE
Allow fine grained control over image plugin sampling

### ISSUE THREAD

**Issue by sleighsoft** [tensorflow/tensorboard#2233]
When creating a `tf.summary.image` across multiple epochs tensorboard will start sampling. This is indicated by the small orange vertical stripes on the grey slider.

![grafik](https://user-images.githubusercontent.com/9438971/57772346-799f1c80-7715-11e9-8f3d-66e390a320cd.png)

This is sometimes very annoying because tensoboard will not show images from the epochs I am interested in.

A slider on the left bar would be nice that allows to set the granularity of sampling or that allows specifing a certain step to allow point selection.

**Comment by wchargin** [comment]
Hi @sleighsoft! Thanks for the report. This is by design, as described
in the FAQ in our README:

<https://github.com/tensorflow/tensorboard#is-my-data-being-downsampled-am-i-really-seeing-all-the-data>

As discussed in the FAQ, the sampling can only be controlled at the time
that you launch the TensorBoard process, not from the frontend. There’s
not an easy way to adjust the granularity or focus on a particular step,
because that data has already been discarded, and we may not even know
what event file it came from.

Please give link that a read; let us know if you have further questions.

**Comment by sleighsoft** [comment]
@wchargin Thanks for pointing that out and sorry for bringing it up again.

tensorboard --help shows db flags being available. Can you maybe elaborate a little more how they work? When using `db_import` does it then allow me to choose from all images on the webpage?
```
  --db URI              [experimental] sets SQL database URI and enables DB
                        backend mode, which is read-only unless --db_import is
                        also passed.
  --db_import           [experimental] enables DB read-and-import mode, which
                        in combination with --logdir imports event files into
                        a DB backend on the fly. The backing DB is temporary
                        unless --db is also passed to specify a DB path to
                        use.
  --db_import_use_op    [experimental] in combination with --db_import, if
                        passed, use TensorFlow's import_event() op for
                        importing event data, otherwise use TensorBoard's own
                        sqlite ingestion logic.
```

**Comment by wchargin** [comment]
The DB flags correspond (as the help texts suggest) to an experimental
TensorBoard mode in which an SQLite database rather than an in-memory
Python object is used as the backing store into which event files are
read. It’s the kind of thing that could eventually support downsampling
on the fly rather than ahead of time, yes, but it’s very much not stable
or guaranteed to work right now. At a glance, it looks like scalars do
have the sampling behavior that you want in DB mode, but I can’t get
images to render at all. ¯\\\_(ツ)\_/¯

**Comment by sleighsoft** [comment]
I hope to see it work sometime in the future :)
