### ISSUE TITLE
How to add email link?

### ISSUE THREAD

**Issue by ceevee830** [tensorflow/tensorboard#2297]
TB version 1.13

Goal: Would like to add an `a href`  link in the TensorBoard GUI that when clicked, allows user to send us an email.

I grepped through the entire code base and did not find any hooks or links or tests that supports any references to any email system.

I'm looking for something like this:

```
<div id="sendEmail">
  We would like to hear from you.  Please contact us at: 
  <a href="mailto:xxx@yyy.com">xxx@yyy.com</a>
</div>
```

When I include a link to an email address in the TensorBoard HTML file, then compile, I get the following bazel compiler error message:

`ERROR: file.html: Referenced mailto:xxx@yyy.com (/path/mailto:xxx@yyy.com) without depending on a web_library() rule providing it`

**Comment by wchargin** [comment]
Hi @ceevee830—thanks for the report. The error message is due to
`rules_closure`. Specifically, the `shouldIgnoreUri` function should
have a case for `mailto:` URLs:

<https://github.com/bazelbuild/rules_closure/blob/21081338d795d2894c59175930a338cda2262260/java/io/bazel/rules/closure/webfiles/WebfilesValidator.java#L212-L223>

I’d suggest sending a PR there. In the meantime, you could work around
this by using something like:

```html
<a href="[[_mailtoUrl(_email)]]">[[_email]]</a>
```

where `_mailtoUrl` is defined on the Polymer element and `_email` is a
constant readonly property with string value `xxx@yyy.com`.

**Comment by ceevee830** [comment]
Thanks!  This is on my current sprint so I'll try it out soon.

**Comment by wchargin** [comment]
@ceevee830: Sounds good. You can cherry-pick #2308 to upgrade the
TensorBoard workspace. Let us know how it goes.
