### ISSUE TITLE
Parse tensorboard graph in an independent program for optimization

### ISSUE THREAD

**Issue by dtchuink** [tensorflow/tensorboard#2303]
HI

I would like to read a Tensorboard graph in an independent program to run some optimization on the graph.

Does Tensorflow provide functions or libraries to read a Tensorboard graph? 

Thanks.

**Comment by rmothukuru** [comment]
@dtchuink ,
Sorry for the delayed response. Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow and Tensorboard version. 

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
