### ISSUE TITLE
TensorBoard not running on colab

### ISSUE THREAD

**Issue by chinmay5** [tensorflow/tensorboard#2350]
Consider Stack Overflow for getting support using TensorBoard—they have
a larger community with better searchability:

https://stackoverflow.com/questions/56606176/tensorboard-projector-not-working-on-colab

I am using colab and although the non GPU version works fine, as soon as I try enabling GPU on the colab notebook, I get errors.

![image](https://user-images.githubusercontent.com/16525717/59556375-ebdb7900-8fc1-11e9-8c44-59aafc04a54b.png)
![image](https://user-images.githubusercontent.com/16525717/59556377-f5fd7780-8fc1-11e9-95bd-59da3a672f1e.png)

**Comment by wchargin** [comment]
Hi @chinmay5! I can’t reproduce this error. On `tf-nightly` from either
yesterday (your SO question) or today, the `projector` import works
fine:

```python
import tensorflow
print(tensorflow.__version__)
from tensorflow.contrib.tensorboard.plugins import projector
print(projector)
```

```
1.14.1-dev20190614
<module 'tensorflow.contrib.tensorboard.plugins.projector' from '/usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/tensorboard/plugins/projector/__init__.py'>
```

This also works fine on TensorFlow 1.13.1 and 1.14.0-rc1.

On the TF 2.0 preview, the import fails because `tensorflow.contrib`
does not exist in TF 2.0, which is to be expected.

You can probably ignore the “already loaded” `%load_ext` warning, unless
you’re doing something funny like reinstalling different versions of
TensorBoard without restarting the runtime.

Can you share the full Colab notebook that you’re using (either as an
`.ipynb` attachment or just a listing of all code cells) that, on a
fresh VM (*Runtimes* menu → *Reset all runtimes*), fails to import the
`tensorflow.contrib.data.python.ops.readers` module?

**Comment by rmothukuru** [comment]
@chinmay5 ,
Can you please let us know if your issue is resolved. 

If not, can you please let us know which version of Tensorflow you are using and can you also share the Google Colab, as requested by @wchargin. Thanks.

**Comment by chinmay5** [comment]
@rmothukuru  sorry for the delay. The only way things kept working was if I reset the runtime and often, shutdown the runtime. The issue still occurs but what I have now is sort of a patch fix.

**Comment by tchaton** [comment]
# Start tensorboard.
%reload_ext tensorboard
%tensorboard --logdir lightning_logs/

**Comment by ftmhabibii** [comment]
Hello, I use Google Club to run the code, but Tensorboard has been giving a 403 error in Google Club for some time. Can you help me to fix this problem?
<img width="719" alt="2023-11-05_134034" src="https://github.com/tensorflow/tensorboard/assets/131171541/95df1317-1462-4c4e-9505-1d28d9d886c6">
