### ISSUE TITLE
Limited tf.compat.v2.summary API due to missing TensorBoard installation

### ISSUE THREAD

**Issue by JCMiles** [tensorflow/tensorboard#2352]
I came across this warning after updating to the las nightly release.
Any idea on how to fix it?

**Comment by wchargin** [comment]
This generally happens if your Python process is running from the
TensorBoard repository:

```
$ python -c 'import tensorflow; print(tensorflow.__version__)'
2.0.0-dev20190617
$ cd ~/git/tensorboard
$ python -c 'import tensorflow; print(tensorflow.__version__)'
WARNING: Logging before flag parsing goes to stderr.
W0617 10:17:07.372941 139892139185984 __init__.py:316] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W0617 10:17:07.384346 139892139185984 __init__.py:343] Limited tf.summary API due to missing TensorBoard installation.
2.0.0-dev20190617
```

This is because the `tensorboard.summary._tf.summary` module can’t be
imported from the TensorBoard repository, because it depends on compiled
proto bindings that are generated by Bazel and are not in the actual
repository root.

Can you reproduce the issue when importing TensorFlow in an empty
directory? If so, please run the `diagnose_tensorboard.py` script and
post the output here, as requested in the issue template.

**Comment by JCMiles** [comment]
Hello,

I'm running this as usual in anaconda environement.
I just executed the cmd pip install --upgrate tf-nightly and get this error.

where is diagnose_tensorboard.py? so I can perform the test and give you more details

**Comment by JCMiles** [comment]
the error persist even if aI create a new conda env
with just pip install tf-nighlty

**Comment by wchargin** [comment]
When you create an issue, the issue template includes the following
instructions:

> Please run `diagnose_tensorboard.py` (link below) in the same
> environment from which you normally run TensorFlow/TensorBoard, and
> paste the output here:
>
> https://raw.githubusercontent.com/tensorflow/tensorboard/master/tensorboard/tools/diagnose_tensorboard.py

(For future reference, it’s really helpful to us if you can read and
follow the template rather than just deleting it. It prevents all this
back-and-forth if we can just get the information up front.)

**Comment by JCMiles** [comment]
thx

### Diagnostics

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version c8952b173fd728c440f0b6bb64c1ecfc87a182b9

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
INFO: os.name: nt
INFO: os.uname(): N/A
INFO: sys.getwindowsversion(): sys.getwindowsversion(major=10, minor=0, build=17134, platform=2, service_pack='')

--- check: package_management
INFO: has conda-meta: True
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tb-nightly==1.14.0a20190614
INFO: installed: tf-nightly==1.14.1.dev20190607
INFO: installed: tf-estimator-nightly==1.14.0.dev2019061701

--- check: tensorboard_python_version
Traceback (most recent call last):
  File "C:\Users\shock\Desktop\workspace\HedaMind-SAC\diagnose_tensorboard.py", line 415, in main
    suggestions.extend(check())
  File "C:\Users\shock\Desktop\workspace\HedaMind-SAC\diagnose_tensorboard.py", line 77, in wrapper
    result = fn()
  File "C:\Users\shock\Desktop\workspace\HedaMind-SAC\diagnose_tensorboard.py", line 230, in tensorboard_python_version
    from tensorboard import version
ImportError: cannot import name 'version' from 'tensorboard' (C:\Users\shock\Desktop\workspace\HedaMind-SAC\tensorboard.py)

--- check: tensorflow_python_version
WARNING: Limited tf.compat.v2.summary API due to missing TensorBoard installation.
INFO: tensorflow.__version__: '1.14.1-dev20190607'
INFO: tensorflow.__git_version__: 'unknown'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'C:\\Users\\shock\\Desktop\\workspace\\HedaMind-SAC\\Tensorboard.bat\r\n'

--- check: readable_fqdn
INFO: socket.getfqdn(): 'SHOCK-DRIVE.lan'

--- check: stat_tensorboardinfo
INFO: directory: C:\Users\shock\AppData\Local\Temp\.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=21673573206770075, st_dev=942234970, st_nlink=1, st_uid=0, st_gid=0, st_size=0, st_atime=1560871209, st_mtime=1560871209, st_ctime=1560871209)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['C:\\Users\\shock\\Anaconda3\\envs\\agent-dev\\lib\\site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.7.1

astor==0.8.0

certifi==2019.3.9

cloudpickle==1.1.1

cycler==0.10.0

decorator==4.4.0

futures==3.1.1

gast==0.2.2

gin-config==0.1.3

google-pasta==0.1.7

grpcio==1.21.1

h5py==2.9.0

Keras-Applications==1.0.8

Keras-Preprocessing==1.1.0

kiwisolver==1.1.0

Markdown==3.1.1

matplotlib==3.1.0

numpy==1.16.4

pandas==0.24.2

pip==19.1.1

protobuf==3.8.0

pyparsing==2.4.0

python-dateutil==2.8.0

pytz==2019.1

pyzmq==18.0.1

setuptools==41.0.1

six==1.12.0

tb-nightly==1.14.0a20190614

termcolor==1.1.0

tf-agents-nightly==0.2.0.dev20190528

tf-estimator-nightly==1.14.0.dev2019061701

tf-nightly==1.14.1.dev20190607

tfp-nightly==0.8.0.dev20190617

Werkzeug==0.15.4

wheel==0.33.4

wincertstore==0.2

wrapt==1.11.1


``````

End of diagnostics.

### Next steps

No action items identified. Please copy ALL of the above output,
including the lines containing only backticks, into your GitHub issue
or comment. Be sure to redact any sensitive information.

**Comment by JCMiles** [comment]
Solved!. a project file was accidentally renamed to tenorboard.py
after renaming the file everything's fine.

**Comment by wchargin** [comment]
I think you mean that one of _your_ project files was actually renamed
to `tensorboard.py` (not `tenorboard.py`), not that one of the
TensorBoard files was accidentally renamed from `tensorboard` to
`tenorboard`. This is apparent from the self-diagnosis output under the
`tensorboard_python_version` check.

Glad that you solved the problem. Again, for future reference, the
answer is immediately apparent from the self-diagnosis output, so in the
future you may find it helpful to follow the issue templates before
posting. :-)

**Comment by sahilpasricja** [comment]
"i ran the diagnosis file and corrects errors it identified , still same issue 

**W0821 16:11:25.460407 139898119034688 __init__.py:328] Limited tf.compat.v2.summary API due to missing TensorBoard installation.**


Here is the output of diagnosis file 

> python diagnose_tensorboard.py 
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version b5843ba83bb708385ff54baaab4b2c70c39f7a4f

--- check: general
INFO: sys.version_info: sys.version_info(major=2, minor=7, micro=15, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): ('Linux', 'sysadmin-ESPRIMO-P920', '4.15.0-58-generic', '#64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019', 'x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tensorboard==1.14.0
INFO: installed: tensorflow==1.14.0
INFO: installed: tensorflow-estimator==1.14.0

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '1.14.0'

--- check: tensorflow_python_version
INFO: tensorflow.__version__: '1.14.0'
INFO: tensorflow.__git_version__: 'v1.14.0-rc1-22-gaf24dc91b5'

--- check: tensorboard_binary_path
INFO: which tensorboard: '/home/pasricha/.local/bin/tensorboard\n'

--- check: readable_fqdn
INFO: socket.getfqdn(): 'sysadmin-ESPRIMO-P920'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: .tensorboard-info directory does not exist

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/home/pasricha/.local/lib/python2.7/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.7.1
asn1crypto==0.24.0
astor==0.8.0
backports.functools-lru-cache==1.5
backports.weakref==1.0.post1
certifi==2019.6.16
chardet==3.0.4
Click==7.0
cloudpickle==1.2.1
cryptography==2.1.4
cycler==0.10.0
dask==1.2.2
decorator==4.4.0
deeplift==0.6.9.0
enum34==1.1.6
Flask==1.0.3
Flask-Assets==0.12
Flask-Cors==3.0.7
funcsigs==1.0.2
functools32==3.2.3.post2
futures==3.3.0
gast==0.2.2
google-pasta==0.1.7
grpcio==1.23.0
h5py==2.9.0
idna==2.8
ipaddress==1.0.17
itsdangerous==1.1.0
Jinja2==2.10.1
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
keyring==10.6.0
keyrings.alt==3.0
kiwisolver==1.1.0
lime==0.1.1.34
lxml==4.3.4
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==2.2.4
mock==3.0.5
networkx==2.2
numpy==1.16.4
opt-einsum==3.0.0
pandas==0.24.2
pandas-datareader==0.7.0
Pillow==6.1.0
pip==9.0.1
playsound==1.2.2
protobuf==3.9.1
pycairo==1.16.2
pycrypto==2.6.1
pygobject==3.26.1
pyparsing==2.4.0
python-dateutil==2.8.0
pytz==2019.1
PyWavelets==1.0.3
pyxdg==0.25
PyYAML==5.1
requests==2.22.0
scikit-image==0.14.3
scikit-learn==0.20.3
scipy==1.2.2
SecretStorage==2.3.1
setuptools==41.2.0
six==1.12.0
subprocess32==3.5.4
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
tensorflow-model-optimization==0.1.2
termcolor==1.1.0
toolz==0.9.0
urllib3==1.25.3
virtualenv==16.6.0
webassets==0.12.1
Werkzeug==0.15.5
wheel==0.33.6
wrapt==1.11.2

``````

</details>

### Next steps

No action items identified. Please copy ALL of the above output,
including the lines containing only backticks, into your GitHub issue
or comment. Be sure to redact any sensitive information.

**Comment by baxterai** [comment]
Issue description (example):

executing;
```python -c 'import tensorflow; print(tensorflow.__version__)'``` 
throws;
```WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation```

I solved the issue by executing [diagnose_tensorboard.py](https://raw.githubusercontent.com/tensorflow/tensorboard/master/tensorboard/tools/diagnose_tensorboard.py);
```python diagnose_tensorboard.py```

**Comment by wchargin** [comment]
Hi @baxterai—thank you for posting! Indeed, the `tensorflow-tensorboard`
PyPI package is a legacy artifact used by TensorBoard versions 1.5.1 and
below only. Removing it and all related packages prior to reinstalling
was the right thing to do. I’ve updated the diagnosis script to detect
this case to help future users in the same situation (#2706). Thanks!

**Comment by m-nasiri** [comment]
My script name was tensorboard.py, i changed the name of file to tb.py solved my problem.

**Comment by andreabac3** [comment]
I have fixed the problem in arch/manjaro with 
`pacman -S tensorboard
`

**Comment by Juneyiiii** [comment]
> 解决了！。重命名文件后，项目文件意外重命名为 tenorboard.py 一切正常。

THANKS! ALREADY SOLVED!
