### ISSUE TITLE
Displaying multiple audio snippets in tensorboard

### ISSUE THREAD

**Issue by MarshmallowFlame** [tensorflow/tensorboard#2469]
I have multiple audio snippets (wav) that I want to display in Tensorboard using tf.summary.audio, but there doen't seem to be a way of getting the players in the same slot/drop-down. With the code below, Im just keeping a list of the audio-summaries, and writing them in order to the tensorboard, hence the players all end up in different drop-downs/slots, with different tag names (even though they are created with the same tag name). Is there a way to get them all together, much the same way as if you input a list of strings into tf.summary.text? Or would it be possible to support html audio tags directly in a tf.summary.text ?

The below screenshot shows what I mean when they end up in different slots.
![image](https://user-images.githubusercontent.com/13196969/61951359-118c7280-afb1-11e9-899a-2616e5096532.png)
Code for the core of what I'm doing, note that there are several class_names that this is done for, therefor the wish to group all the snippets of one class together. 
```ids = ["list","of","ids"]
class_name="class name"
audio_sums = []

for id in list_of_ids:
    audio_dec = librosa.load(id+".wav")
    audio_summary = tf.summary.audio(class_name+" sample", tf.expand_dims(audio_dec[0], 0),
                                         tf.constant(audio_dec[1], dtype=tf.float32), max_outputs=1)
    audio_sums.append(audio_summary)


with tf.Session() as sess:
    writer = tf.summary.FileWriter(os.path.join(job_dir, 'logs'), sess.graph)

    for a in audio_sums:
        b = sess.run(a)
        writer.add_summary(summary=b)

    writer.close()
```

**Comment by txntxn** [comment]
I am also interested in this.

**Comment by wchargin** [comment]
One easy approach is to set the tag filter to `24gabber_.*` in your
example, or just `.*` in general. This will create a new “category”
(i.e., slot/drop-down) that has all the audio clips.

It also suffices to just give all the audio clips a common group name:
e.g., if instead of calling them `24gabber_sample_N` you call them
`24_gabber/sample_N`, the slash-delimiter will create a `24gabber`
category.

You can also do this at write time by passing all the audio clips to a
single summary operation. See the [`tf.summary.audio` docs][1], noting
in particular the “`k` (number of audio clips)” dimension of the input.

[1]: https://www.tensorflow.org/api_docs/python/tf/summary/audio
