### ISSUE TITLE
Feature request: display images at true size

### ISSUE THREAD

**Issue by goodfeli** [tensorflow/tensorboard#256]
I'd like to be able to view images in TensorBoard at that their true size (1 pixel in tensor = 1 pixel on monitor). I'd also like to be able to make this the default. The current default is to rescale them, which introduces scaling artifacts. When evaluating image generation models, it can be hard to tell which artifacts are defects in the model and which are caused by Tensorboard. Currently, there's a button you can click that shows the image at true size in a separate window and grays out all the other elements on the page. I'd like to be able to just switch the normal tensorboard display to use this size, so that I can see more than one image at that size simultaneously, I can drag the history slider and watch the image evolve at correct size, etc.

**Comment by chihuahua** [comment]
I originally added the "lightbox" feature which overlays the actual size against a dark background because some folks (I believe working on image compression) needed to observe for artifacts in the actual size (which I think is similar to your motivation here).

I then conducted some user tests (focus groups). No subjects actively mentioned the feature, though some users did wish for a way to compare between individual steps of an image. Overall, I support your feature. Let me put together a PR and a demo.

**Comment by wchargin** [comment]
Closing this because #261 is merged. We can reopen if it's determined that we need more work here.
