### ISSUE TITLE
Let's not show tags matching /.*/ (all tags) by default

### ISSUE THREAD

**Issue by norouzi** [tensorflow/tensorboard#270]
Tensorboard has switched to showing all of the summaries i.e. "Tags matching /.*/ (all tags)" by default as the default window. This is annoying and slow for jobs that have quite a few summaries. I don't this should be the default window.

**Comment by wchargin** [comment]
Thanks for your input. The goal of defaulting to `.*` was to always display _some_ data instead of hiding everything behind collapsed categories. But I can see that if you're carefully categorizing your tags and have a large number of tags at top level, it could be more useful to keep everything collapsed.

I hope that it shouldn't be too slow for jobs with many summaries—we should only display twelve charts due to pagination, correct?

**Comment by dandelionmane** [comment]
Note: I also had other people internally saying the same thing to me, and norouzi mentioned at least one other person making the same request. The request seems pretty widespread, so my default course of action is that we should show an empty search.

**Comment by norouzi** [comment]
Yes, by default only 12 summaries are shown, but 12 summaries are already
enough for them to take a while to load, especially given that I run a
single tensorboard for a collection of tasks. The bigger issue is that with
the collapsed format I can request to see the important summaries which
maybe the last ones, and often prefer to look at those summaries in the
enlarged form...

**Comment by Marvin182** [comment]
I'm strongly with Mohammad here. The current default is annoying for me and many peers. I understand the good intention of displaying always some information but falls to the fact that most boards will have more than 12 summaries.
1) With more than 12 summaries you quickly end up in the state that the first 12 (in alphabetical order) are not the interesting ones. Then you have to scroll down or correct the filter. And many people will have to do that many times a day.
2) Even with <=12 summaries it might be more convenient to just show the interesting ones because other shards just cluster the display and distract. E.g. many of my boards will have a summary if the queues for reading input are full. Unless I suspect problems I don't want to see this.
3) From a user interface perspective it's not intuitive to have a filter option and just filter for everything.
4) 6*2 summaries is to much for many screens, so you have to scroll within a page.

**Comment by ticcky** [comment]
@wchargin I'm not sure I understand why is it good to "show at least something"? This adds another click that I **always** need to do every time I go to TensorBoard. Could this be a] a web-browser setting that will be remembered forever, b] CLI flag? I'm sure such solution would satisfy all users :)

**Comment by Marvin182** [comment]
also see #294

**Comment by wchargin** [comment]
Yep, we totally hear you and are happy to revert this behavior. How about making the default search query `""` instead of `".*"`, which will have the effect that no search result pane appears at all by default?

**Comment by Marvin182** [comment]
That would be great.

**Comment by lespeholt** [comment]
That would indeed be great. Plenty of people here at DeepMind are also complaining about this. The first I do as a default when looking at TensorBoard is collapsing the search pane as quickly as possible before things get slow.
