### ISSUE TITLE
Which version to fork for new viz development?

### ISSUE THREAD

**Issue by BinhangYuan** [tensorflow/tensorboard#272]
I forked the master branch for my own visualization development.

I found that after compiling this branch, only GRAPHS and PROJECTOR functionality works for my model. SCALES and HISTOGRAMS does not work anymore.

I previously used the pre-installed tensorboard to visualize the model by all the above views. 

Additionally, I found this branch cannot even visualize the data generated by the scalars_demo.py script. This is probably similar to #271. My situation is that the page complains that "No scalar data was found."  See the photo here: 
![screenshot from 2017-07-26 17-46-07](https://user-images.githubusercontent.com/6721177/28615057-6cc2f8d4-722a-11e7-85db-e4d56d476cca.png)

Any suggestion is highly appreciated!

**Comment by wchargin** [comment]
Hi Binhang,

Happy to hear that you're interested in developing a new plugin!

Instead of forking the repository, you'll want to follow the instructions in [tensorflow/custom-tensorboard-example](https://github.com/tensorflow/tensorboard-plugin-example). That repository has a fully self-contained example plugin, and also has reasonably detailed instructions about how plugin development works.

Are you saying that when you check out the master branch of this repository, unchanged, and then run `rm -rf /tmp/scalars_demo && bazel run //tensorboard/plugins/scalar:scalars_demo && bazel run //tensorboard -- --logdir /tmp/scalars_demo --port 6006`, and then wait ten seconds before launching TensorBoard, then the resulting TensorBoard instance does not show scalar data? If this is the case, please specify details of your environment: your OS, your Python version, and the version of TensorFlow installed in your virtualenv.

**Comment by BinhangYuan** [comment]
Oh, instead of run `bazel run //tensorboard/plugins/scalar:scalars_demo`, I run python `./tensorboard/plugins/scalar/scalars_demo.py`, I guess this should not matter. 

And actually, I re-run it as you suggested, it has the same problem.

I used a Ubuntu 16.04 LTS OS, with python 3.5.2 and Tensorflow 1.2.1.

BTW, I also found this repository (https://github.com/jart/web_library_example) in another post #130  . Is this also abandoned?

Thanks for your reply! I really appreciate your help!

**Comment by wchargin** [comment]
> I guess this should not matter

Nope, this absolutely matters. You need to use Bazel so that it can build the dependent targets. For instance, Bazel compiles protobufs into Python modules so that we can import them and use the bindings from Python code. If you just use `python my_file.py`, then these files will never be created or linked to your Python environment, so the code will fail.

> I re-run it as you suggested, it has the same problem.

Your TensorFlow version is out of date. You need to install TensorFlow from its nightly builds. See: https://github.com/tensorflow/tensorflow#installation

**Comment by wchargin** [comment]
jart/web-library-example should still work, but would only be relevant if you're starting a new non-TensorBoard project in which you want to use the `ts_web_library` build rule. Within TensorBoard, you have our workspace file and everything, so you can simply look at existing build rules within this project for reference.

**Comment by BinhangYuan** [comment]
@wchargin ! Thanks for pointing that out!
