### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'train'

### ISSUE THREAD

**Issue by aghamohamadi** [tensorflow/tensorboard#2820]
from train import train_model

AttributeError: module 'tensorflow' has no attribute 'clip_by_average_norm'

what's this?
I don't know

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!
