### ISSUE TITLE
Questions about new jQuery plugin architecture

### ISSUE THREAD

**Issue by ceevee830** [tensorflow/tensorboard#2821]
So I'm working on getting our business data from the back-end into the UI using the new jQuery support.  

1) The back-end to my plugin was modeled after the GRAPHs plugin whereby it delivers business data via protobuf format.  `return (str(gpu_summary), 'text/x-protobuf')  # pbtxt` 
But the example [index.js here](https://github.com/tensorflow/tensorboard/blob/ab7f72a643fb8e9073f857a7d6579d016bbfd223/tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/static/index.js#L20) accepts json-formatted payload.  Question: How can I update my index.js to parse incoming data as protobuf?

2) Also, do you have a design document or something that describes how `export async function render()` is called in the index.js?

Thanks,
-Chris

**Comment by rmothukuru** [comment]
This issue doesn't seemed to be related to Tensorboard. If so, please raise the issue in the respective Repository of Github.

If you feel this issue is related to Tensorboard, Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in the Github new issue template.

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by psybuzz** [comment]
Thanks for the question!  I'm not familiar with "new jQuery support", but the rest of the question is TB related.

1.
The Graph dashboard has its own frontend logic to parse protobuf txt from the backend.  [parser.ts](https://github.com/tensorflow/tensorboard/blob/f88ad58003f9480e9f18ed852559f14ffc77e435/tensorboard/plugins/graph/tf_graph_common/parser.ts#L89) will fetch a response and call `res.arrayBuffer()` and transform it into a usable form via `parsePbtxtFile`, instead of `res.json()`.  If you wish to roll your own solution, this implementation could be a reference.

There are also 3rd party protobuf libraries to investigate, which might also address your needs, e.g.
https://github.com/protobufjs/protobuf.js

2.
Although the plugin example repo shows how to define it, I can look into making the documentation better.  Right now, TensorBoard simply imports the plugin's entry point as a module and [calls](https://github.com/tensorflow/tensorboard/blob/f88ad58003f9480e9f18ed852559f14ffc77e435/tensorboard/components/tf_ng_tensorboard/plugins/plugins.component.ts#L147) `render()`.

Sidenote: if you have more ideas, questions, feedback on how the dynamic plugin authoring experience could be better, please add comments to https://github.com/tensorflow/tensorboard/issues/2357 !

**Comment by rmothukuru** [comment]
@ceevee830,
Can you please let us know if @psybuzz's comment has clarified your query, so that we can work towards Closure of this issue. Thanks!

**Comment by ceevee830** [comment]
Thanks, Team.  I am able to read the back-end payload in JSON format.
