### ISSUE TITLE
TensorBoard - how to show all histograms?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [tensorflow/tensorboard#2983]
My ResNet logs 200+ histograms, which I must click individually to view - example below. This is quite inconvenient to repeat each time - is there a quicker option (e.g. a button, a command-line argument)?

<img src="https://i.stack.imgur.com/7U2Eb.png" width="550">

**Comment by nfelt** [comment]
There's no automatic way to expand all the histogram panes at once, no - the expandable pane grouping logic assumes that related data would be grouped by a filename-style prefix (so e.g. if the summary names were `batch_norm/1`, `batch_norm/2` it would put them in a `batch_norm` pane for you, but it doesn't do this for underscore prefixes).

As a workaround you could specify a tag filter of `.*` (it's a regex that matches all tags) so that they all appear under the single search results pane at the top.  This will show as many histograms as your configured pagination limit, and you can set that in the gear icon settings menu to as high as you want, although TensorBoard may get pretty slow if you show 200 at once.

**Comment by OverLordGoldDragon** [comment]
@nfelt Excellent, thank you
