### ISSUE TITLE
Nothing shows up in my local jupyter notebook.

### ISSUE THREAD

**Issue by Bee-zest** [tensorflow/tensorboard#3030]
I can successfully run the demo script ```COMPAS Recidivism Classifier``` in the jupyter notebook on my local machine. But nothing shows up at the end of jupyter notebook. I assume it will show up the visualization interface after I run ```WitWidget(config_builder, height=tool_height_in_px)```. 

And I install all the extension at the beginning of the jupyter notebook(python3). 
```! pip install witwidget
! jupyter nbextension install --py --symlink --sys-prefix witwidget
! jupyter nbextension enable --py --sys-prefix witwidget
```

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by rmothukuru** [comment]
@Bee-zest,
Can you please provide the details mentioned above. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
