### ISSUE TITLE
How can I save the tensorboard pages as html

### ISSUE THREAD

**Issue by HisiFish** [tensorflow/tensorboard#321]
I want to save the tensorboard pages of some popular models as html.

**Comment by HisiFish** [comment]
So others can view different DNN models in one entrance just by click.

**Comment by zihaolucky** [comment]
Have you tried to save it directly from Chrome or Safari? Did it work?

**Comment by wchargin** [comment]
If your goal is to show the results from many different models, you could just launch a TensorBoard with all of them. If you have logs in `/tmp/logs/model1`, `/tmp/logs/model2`, etc., then instead of using `--logdir /tmp/logs/model1` just use `/tmp/logs`, and TensorBoard will combine data from all your models. You can use the run selector in TensorBoard to filter which runs you see at any given time. Does this make sense?

I would not expect saving the HTML of a TensorBoard page to work well at all. The TensorBoard web page needs to be in constant communication with the TensorBoard server. The data displayed in TensorBoard is fetched by JavaScript at runtime, not stored in the page at serving time.

**Comment by HisiFish** [comment]
@wchargin Thanks. Excellent solution!

**Comment by HisiFish** [comment]
@zihaolucky Thanks for your reply. It does not work if I only save it from Chrome.
