### ISSUE TITLE
tensorboard.dev uploader: one-shot upload mode

### ISSUE THREAD

**Issue by caisq** [tensorflow/tensorboard#3306]
Currently tensorboard.dev (Hosted TensorBoard) uploader does not exit; it keeps running and listening for new data logged to the logdir, and the user needs to manually interrupt it with Ctrl+C to make it stop. It will be nice and useful to have a one-shot upload mode, in which it just uploads all the currently-available data in the logdir and exits cleanly like a typical command-line tool. This is useful for automation and cases in which the training job is done and the user just wants to upload it to tensorboard.dev for archival or sharing.

**Comment by nfelt** [comment]
FYI a related feature I'd had in mind would be to use the "inactive" file status (from the new `--reload_multifile` functionality, which the uploader has on by default) to automatically stop the upload once it looks like new data is no longer being added.

This would usually cover the "upload historical data" case since those event files would be detected as inactive.  It's true though that it wouldn't cover the case of freshly generated data.

**Comment by caisq** [comment]
This is fixed by #3707
