### ISSUE TITLE
Tensorflow compat protos are out of sync

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tensorboard#3391]
Changes in tensorflow made mostly in:
https://github.com/tensorflow/tensorflow/commit/4221d1aa4d20ada495771528bb13ca786d0bdbe0#diff-c20846a7704549bba232c5b2ff86de25

**Comment by wchargin** [comment]
For a bit of context: this is expected to happen. We pin copies of the
protos, but TensorFlow can freely update them at any time, subject to
backward compatibility constraints. The proto compat test is tagged as
`manual` to prevent non-hermetic churn, but we run it as part of our
release process so that we’re at least aligned for full releases and to
prevent any discrepancies from growing large without us noticing for too
long.

The proper fix is:

 1. In your TensorFlow clone, check out the version of TensorFlow whose
    protos you want to update (e.g., `git checkout v2.2.0-rc0`).

 2. In your TensorBoard repo, run:

    ```
    ./tensorboard/compat/proto/update.sh PATH_TO_TENSORFLOW_REPO
    ```

    (where `PATH_TO_TENSORFLOW_REPO` is, e.g., `~/git/tensorflow`).

  3. Review and commit any changes.

We should probably add a mention in the test failure that you can just
run the update script to resolve these automatically.
