### ISSUE TITLE
NameError: name 'sess' is not defined - file_writer = tf.summary.FileWriter('/path/to/logs', sess.graph)

### ISSUE THREAD

**Issue by mikechen66** [tensorflow/tensorboard#3634]
Consider Stack Overflow for getting support using TensorBoard—they have
a larger community with better searchability:

https://stackoverflow.com/questions/tagged/tensorboard

Do not use this template for for setup, installation, or configuration
issues. Instead, use the “installation problem” issue template:

https://github.com/tensorflow/tensorboard/issues/new?template=installation_problem.md

To report a problem with TensorBoard itself, please fill out the
remainder of this template.

## Environment information (required)

Please run `diagnose_tensorboard.py` (link below) in the same
environment from which you normally run TensorFlow/TensorBoard, and
paste the output here:

https://raw.githubusercontent.com/tensorflow/tensorboard/master/tensorboard/tools/diagnose_tensorboard.py

For browser-related issues, please additionally specify:

  - Browser type and version (e.g., Chrome 64.0.3282.140):
  - Screenshot, if it’s a visual issue:

## Issue description

Please describe the bug as clearly as possible. How can we reproduce the
problem without additional resources (including external data files and
proprietary Python modules)?

**Comment by nfelt** [comment]
This doesn't contain enough detail to understand whether this is a TensorBoard issue.  Glancing at the issue title, it doesn't sound like one, because the NameError is about the variable `sess` which is an argument to the call to `FileWriter`, so it's failing before it even makes the call.

If you believe there's a bug in TensorBoard, please elaborate on what it is, and fill out the environment information as requested in the issue template.
