### ISSUE TITLE
graph viz TPU compatibility coloring is badly broken

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#408]
To repro, select a node and color by TPU compatibility. Then, click on empty space in the scene to deselect the node. The card for TPU compatibility will unfortunately linger.

![gb8ugjxosk9](https://user-images.githubusercontent.com/4221553/29655151-cfa7bb60-8864-11e7-83c1-e7ce49bba1a7.png)

**Comment by nfelt** [comment]
So not only is this not fixed (the op card still lingers after deselecting), entering TPU compatibility mode wreaks havoc with the positioning of all the edges, causing them to get offset when trying to click to expand a node (while coloring by TPU compat), and the node itself doesn't expand.  Sample broken graph, using the graph produced by the scalars_demo.py code:

![image](https://user-images.githubusercontent.com/710113/71040969-b6ccf200-20dc-11ea-8ad9-574be0fc93ec.png)

**Comment by psybuzz** [comment]
I think the behavior in the OP's description is mostly intended. The TPU compatibility pane persists, even when no node is selected, because it shows the overall graph-wide compatibility, across all nodes.

If that's the case, is this safe to close?

**Comment by psybuzz** [comment]
The issue described in comment#1 is intended for now, as the TPU compatibility pane for the whole graph is not supposed to hide when nodes are deselected.  Whether this is the best UX overall for showing graph-level compatibility is a larger question.

The issue described in comment#2 was fixed in https://github.com/tensorflow/tensorboard/issues/2900

Closing this report.
