### ISSUE TITLE
Tensorboard.dev upload to specified experiment ID

### ISSUE THREAD

**Issue by gzerveas** [tensorflow/tensorboard#4081]
Currently, there is no way to upload new data to an existing experiment once the tensorboard client has been interrupted. However, this use case comes up very often (e.g. running a bunch of hyperparameter search experiments, then another bunch, or implementing a new model a few days later and wanting to compare). The only solution is to delete the older experiment and start a new experiment, assuming that the data exist on the same machine. This brings us to the second benefit: in case one is performing experiments on different machines, it is a lot more convenient to upload all to the same URL/experiment ID, than to aggregate the data (or mount the remote drives) on a single machine and then upload them to an experiment.
The proposed functionality would be evoked like this:
`tensorboard dev update --experiment_id EXPERIMENT_ID --logdir logs`

**Comment by bileschi** [comment]
Thank you for your feature request @gzerveas, this is a request we have heard from several users, and something we will prioritize.

**Comment by kryptonite0** [comment]
up this, would be really cool to have this functionality

**Comment by bileschi** [comment]
Tested a flow on this today, looks like it may be possible.  Need to work around a few side effects.

**Comment by asanc199** [comment]
Hi! How is this going? I'm trying to upload more logs to my experiment and i'm trying to look some answers. Hope it is going good!

**Comment by bileschi** [comment]
Hello @asanc199 ,  Sorry this got dropped for more urgent matters.  We should be able to get to this in Q2.

**Comment by versae** [comment]
Updating an experiment from different machines would be a really nice feature. Any update on or branch to test this?

**Comment by bileschi** [comment]
Hello @versae , agreed it would be really nice, but sorry to disappoint.  We've been focusing on other matters, such as the new [experiment list](https://tensorboard.dev/experiments) feature.  Hopefully that helps a little in keeping track of multiple experiments.

The feature to upload to an existing experiment is made complicated by the semantics of what happens when the same run is uploaded multiple times.  In OSS TensorBoard, different runs exist in different directories, but in TensorBoard.dev, it's possible to overwrite the same run, leading to very strange behavior, where the data is overwritten or out of order.  It's possible users would want different things in different circumstances (overwrite vs. clone).

The changes would mainly be where setting & access to this `experiment_id` property happen in the uploader.  Presumably it would read from a flag in certain settings.   https://github.com/tensorflow/tensorboard/blob/2c372becadf61ac6e7de4ed2542a510123028c6a/tensorboard/uploader/uploader.py#L165

Again, care needs to be taken in edge cases.  (Updating an experiment you don't own, Overwrite vs. clone, inserting out-of-order data points).

I expect we will get to this eventually, but contributions are welcome.

**Comment by versae** [comment]
I understand. Thanks for the detailed answer, @bileschi! Since we have all our machines cross-mounted and sharing their disks over NFS, a low-key solution could be symlink in a folder each run and pass in the proper params to `logdir`. Something along the line of `--logdir machine1:/nfs/machine1/logs,machine2:/nfs/machine2/logs`.

**Comment by AmoghDabholkar** [comment]
Hey guys
Any update on this?

**Comment by nfelt** [comment]
No updates to share at this time, I'm afraid.

**Comment by adzcai** [comment]
Hi, any updates?

**Comment by kmtm** [comment]
Also looking for updates :)

**Comment by bileschi** [comment]
Googlers, this is b/266594526

**Comment by Butanium** [comment]
Still no updates ?
