### ISSUE TITLE
notebook.list() lists a non-existent instance

### ISSUE THREAD

**Issue by caph1993** [tensorflow/tensorboard#4187]
Dear developers, the following is not a crucial bug, and I think it is very easy to fix.

For some reason, when I ran `notebook.list()` I got an instance that was already killed. I can't reproduce the problem easily, but I have the logs. At a point, `notebook.list()` listed **two instances over the same port**, which is impossible. In reality, **one of the processes did not exist on my OS** as it was killed long before.

This snippet summarizes what happened:

```python
from tensorboard import notebook
notebook.list()
'''Printed this (weird):
Known TensorBoard instances:
  - port 6006: logdir logs (started 0:13:03 ago; pid 67178)
  - port 6006: logdir logs (started 1:22:04 ago; pid 18101)
'''
# Explanation:
import os
os.kill(67178, 0) # OK, returned None
os.kill(18101, 0) # Raised ProcessLookupError: [Errno 3] No such process
```

I think you could add a call to `os.kill(instance.info.pid, 0)` inside the function `notebook.manager.get_all` to check if the process does actually exist before appending the instance to the list.

**Comment by wchargin** [comment]
Hi @caph1993! Thanks, and you’re right—I think we’re tracking this more
broadly at #2483. An `os.kill` approach could work, but we do try to
support Windows, so we have to be a bit careful with signal support
there. A perhaps safer approach is to try to talk to the TensorBoard
server on the listed port.

I’m going to close this since I think #2483 covers it, but please let me
know if you disagree. Thanks!

**Comment by caph1993** [comment]
I agree: this issue is covered by issue #2483.
Thank you.
