### ISSUE TITLE
[question] convert bookmark json to scatter coordinates

### ISSUE THREAD

**Issue by Pzoom522** [tensorflow/tensorboard#4337]
Hi,

After using the projector to visualise my embeddings (via 3d PCA), I manually rotate the result and save **the best "pose"** in a bookmark json. Is it possible for me to use this json file to calculate a 2d matrix, so that I can plot/restore the same pose (i.e., the one I just pick on the screen) using tools such as matplotlib? How?

Many thanks!

**Comment by Pzoom522** [comment]
It's also ok if you can let me know a way to save the embedding visualisation as a **high-resolution**  file, e.g., PDF or SVG. Many thanks!

**Comment by bmd3k** [comment]
Hi Pzoom522, by high-resolution do you mean something that is vector-graphics based? Or would a PNG suffice?

The bookmark file contains information that should allow you to partially reconstuct the view. It contains principal components of all points (tuples of {"pca-0", "pca-1", etc..}). There is a map of principal components to the X,Y, and Z axes (I think "pcaComponentDimensions"). It also contains information about where the camera lies and which target it points to ("cameraDef"). Unfortunately it does not contain labels of the points, if you needed those.

I don't think you necessarily need to build your own 2D matrix. Ideally you would use a 3D visualization library that takes care of most of the heavy lifting for you. I don't have a particular python library to recommend.

**Comment by hfiller** [comment]
Hi!

It should be possible to do this with the data in the bookmark.
- **Projections**: this field contains all of the points in your embedding. You can use `pca-0`, `pca-1` and `pca-2` as your x, y and z coordinates.
- **CameraDef**: this contains information about the "pose" that you have moved the camera to. Specifically the **target** (what the camera is looking at) and **position** (the position of the camera)

In order to get the projection, you can use the [LookAt function](https://www.geertarien.com/blog/2017/07/30/breakdown-of-the-lookAt-function-in-OpenGL/) to get a ViewMatrix, then multiply every point by that to get something in CameraSpace. Once it's in cameraspace, you can use a projection to get a 2D version of the API.

I've put together [a basic gist that does this](https://gist.github.com/hfiller/9cfcb3ff6fa0cf7166767092bbd230c8)

**Comment by Pzoom522** [comment]
Hi @hfiller and @bmd3k, many thanks for your reply!
> Ideally you would use a 3D visualization library that takes care of most of the heavy lifting for you.

The main reason I need to export plots via Embedding Projector because it is **interactive**, which is much easier to use than a static visualisation tool when I'm looking for the best position.

> I've put together a basic gist that does this

Much appreciate! I'll check your gist. 

Close this issue for now.
