### ISSUE TITLE
Problems with upload

### ISSUE THREAD

**Issue by DiogoSemedo** [tensorflow/tensorboard#4400]
I uploaded the same local data to tensorboard.dev but the graphics are different, what is the problem ?
![issue](https://user-images.githubusercontent.com/43584520/100523862-80ab4580-3168-11eb-827a-17b9a3758936.png)

**Comment by psybuzz** [comment]
Thanks for filing this.  From the screenshot, it looks like the upload sent only a few steps of data successfully.  Could you please let us know:

- Are you running TensorBoard from the terminal?  (e.g. not in a notebook/Colab)
- Was your `tensorboard dev upload` command running _while_ your script was continuously writing training/eval logs?  Or was the `tensorboard dev upload` command run after all the steps were written?
- If the logdir is non-sensitive, would it be possible to share so that we could reproduce the issue?
- Could you please run the following diagnosis script, so that we can see the Python version, TensorBoard version used?
https://raw.githubusercontent.com/tensorflow/tensorboard/master/tensorboard/tools/diagnose_tensorboard.py

**Comment by DiogoSemedo** [comment]
> Thanks for filing this. From the screenshot, it looks like the upload sent only a few steps of data successfully. Could you please let us know:
> 
>     * Are you running TensorBoard from the terminal?  (e.g. not in a notebook/Colab)
> 
>     * Was your `tensorboard dev upload` command running _while_ your script was continuously writing training/eval logs?  Or was the `tensorboard dev upload` command run after all the steps were written?
> 
>     * If the logdir is non-sensitive, would it be possible to share so that we could reproduce the issue?
> 
>     * Could you please run the following diagnosis script, so that we can see the Python version, TensorBoard version used?
>       https://raw.githubusercontent.com/tensorflow/tensorboard/master/tensorboard/tools/diagnose_tensorboard.py

I was running it from the terminal, and the command was run after all the steps were written. 
Anyway I think the reason behind is that when I make the upload the average is computed and it doesn't upload all values.
Here is the data:
[DAgger_18_7.29.53.zip](https://github.com/tensorflow/tensorboard/files/5622470/DAgger_18_7.29.53.zip)

**Comment by bileschi** [comment]
Hi @DiogoSemedo !  It appears that the data you have provided only includes the run `DAgger_18_7.29.53`, but your board and screenshots indicats you are interested in more runs than this.

https://tensorboard.dev/experiment/WSNUKVbnQt2jty1NUPRJiw/#scalars&run=FlappyBird%2FDAgger_18_7.29.53&runSelectionState=eyJGbGFwcHlCaXJkL0RBZ2dlcl8xOF83LjI5LjUzIjpmYWxzZSwiRmxhcHB5QmlyZC9EQWdnZXJfMjVfNy4yOS41OCI6ZmFsc2V9

Can you verify that you have zipped the correct directory?
Thanks

**Comment by bileschi** [comment]
FYI : TensorBoard as run locally should show the same scalars as TensorBoard.dev

**Comment by rmothukuru** [comment]
@DiogoSemedo,
Can you please respond to above comments. Thanks!
