### ISSUE TITLE
Web UI: +`<noscript>` warning

### ISSUE THREAD

**Issue by gwern** [tensorflow/tensorboard#4401]
I use NoScript & sometimes load up a Tensorboard on a new IP or domain. Every time I forget that TB requires JS and am briefly puzzled by the completely blank screen.

It would be nice to add a little warning somewhere in the HTML source:

~~~.HTML
<noscript>ERROR: Tensorboard requires Javascript; enable JS and reload.</noscript>
~~~

(I checked the HTML source of a TB I'm running now and consistent with my observation of a blank screen, I see no warnings already.)

**Comment by wchargin** [comment]
Good point; thanks! Sent #4401.

On a somewhat related tangent: I know that you often archive and mirror
resources that you link to from your web pages, which is a lovely
practice, imho. If you’re interested in mirroring TensorBoard instances
so that they can be viewed without a live backing server, let us know
and we can maybe advise. One easy option is to use [TensorBoard.dev] as
the hosting provider and just link to that, but if you want a fully
local mirror, there may be alternatives. For instance, a Colab notebook
with a `%tensorboard` cell will log the network requests that the
TensorBoard frontend makes to the backend, save them in the notebook
itself, and replay them when the notebook is reopened.

[TensorBoard.dev]: https://tensorboard.dev/
