### ISSUE TITLE
Smoothing weighted incorrectly

### ISSUE THREAD

**Issue by shurickdaryin** [tensorflow/tensorboard#4481]
When smoothing a scalar plot, apparently a higher weight is given to the first point. This means that, if there is steep change in the beginning of the graph, the smoothed line will be significantly off the unsmoothed data, and will only slowly move in that direction:

![image](https://user-images.githubusercontent.com/2276915/102260251-8185fa80-3f10-11eb-9574-f4f2577df85f.png)

One possible way to fix that would be to also smooth the point count (the same way the values are smoothed) and divide by that. There are of course many other alternative approaches.

**Comment by nfelt** [comment]
Thanks for bringing this up - we realize the smoothing algorithm is pretty imperfect, despite being the product of several earlier iterations (see #610 for some of this history).  There are a few open issues that might already cover the issue you describe, in particular #1127 seems like probably an even simpler case that we don't really handle right (due to biasing too much on the initial value).  So if that seems to fairly capture the issue to you, we can mark this as a duplicate.

**Comment by shurickdaryin** [comment]
Yes, #1127 seems to refer to the same problem so this bug is probably a duplicate.

**Comment by rmothukuru** [comment]
@shurickdaryin,
Closing this issue as it is already being tracked in #1127. Thanks!
