### ISSUE TITLE
A comment in the Source Code of Profiler is misleading

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/tensorboard#4498]
Hi,
The Note in [the Line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/profiler/tfprof_log.proto#L129-L130) is being misinterpreted that the Statistics Generated by Tensorboard Profiler are wrong.

Please refer the below comment in https://github.com/tensorflow/tensorflow/issues/42584:

> I also came across tf.Profiler, but it has this comment saying that numbers are not reliable, which otherwise might have sufficed the requirement.

Is it really the case? If not, I think [the comment](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/profiler/tfprof_log.proto#L129-L130) needs to be modified.

I will be happy to submit a PR if required. Thanks!

**Comment by nfelt** [comment]
I don't think this question should be filed under the TensorBoard issue tracker - the TF Profiler is its own team, and while the UI for the profiler is a TensorBoard plugin, the profiler itself is largely an independent project.  The code comment here applies to code that really has nothing to do with their TensorBoard integration, so I think this question would be better asked at https://github.com/tensorflow/profiler/issues or directly to the profiler team.

That said, I'm not sure you will get a clear answer since xpan (the person mentioned in the TODO) no longer works on the profiler.  However, I wouldn't assume that the comment is necessarily "misleading" or appropriate to remove - unless you hear back that the accuracy issues have indeed been fixed, I would assume they still apply.
