### ISSUE TITLE
Can't run vz-line-chart in demos (plugin development related)

### ISSUE THREAD

**Issue by gar1t** [tensorflow/tensorboard#455]
I'm working on a plugin for TensorBoard that uses the vz-line-charts and I'm unable to test the work using `bazel run DEMO_TARGET` as I get the following error in the browser:

```
Uncaught SyntaxError: Unexpected token export vz-chart-helpers.js:15
```

As I understand it, the JavaScript generated by the TypeScript compiler is considered a module (it contains top-level exports) and therefore won't work in browsers without a module loader. As vulcanize inlines everything, this problem doesn't show up in the distribution, just in development workflow.

How does Google deal with this when developing components? Even with small components, vulcanize takes quite a while to run and the generated file is impractical for debugging. I'd like a work flow that simply supports a browser refresh after a file edit. Apart from the module problem described here, this works well using `bazel run DEMO_TARGET`.

Any thoughts on how to with with these modules using this (or a similar) dev workflow?

**Comment by chihuahua** [comment]
Unfortunately, our workflow requires vulcanization because the `ts_web_library` rule vulcanizes as a subroutine. So far, we haven't made use of intermediary outputs like that of the TS compiler.

@jart, I wonder if we can somehow make this flow easier for developers. Long ago, we could start a demo for just 1 component instead of having to vulcanize all of TensorBoard.

**Comment by wchargin** [comment]
I agree that it's suboptimal. Within Google, we just work with it. Note that the generated file becomes much more debuggable if you [ask Chrome to pretty-print it.](https://developers.google.com/web/tools/chrome-devtools/javascript/reference#format) ([Firefox has an equivalent feature.](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Pretty-print_a_minified_file)) Variable names are minified, but property names never are, so you can quickly find a piece of code by looking for a nearby `foo.somewhatUncommonPropertyName` in your source and <C-f>ing for `.somewhatUncommonPropertyName`. It's not the best, but it does the job.

I feel your pain, though, and would be very happy if we had some sort of incremental vulcanization.

**Comment by chihuahua** [comment]
You just reminded me - if you `bazel run` a `ts_web_library` target (for instance, `bazel run tensorboard/plugins/pr_curve/tf_pr_curve_dashboard:tf_pr_curve_dashboard`), you start a local webserver (localhost:6006). We have not taken advantage of that though, and I don't believe we have plans to document that. That's how we used to run demo rules.

For a while, we followed the polymer demo pattern, but we forwent it due to some difficulties with open sourcing. That is why we have demo directories lingering about. One complication was that internal build rules for TypeScript at the time lacked support for modules, so we made our own custom rules. And you're right - `tensorboard_html_binary` vulcanizes.

**Comment by gar1t** [comment]
Yes, I've been using the "run" command to successfully run "demos", but as soon as I run into an ES6 module I hit the problem of module code being read in a non-module context. Adding 'type="module"' to any scripts that touch ES6 modules sets that right, but then there are the namespace issues with non-ES6 module code. So it does look like a vulcanize step is necessary to work in this world.

Is there a general goal within the TensorBoard project to move everything to ES6 modules?

**Comment by chihuahua** [comment]
@jart

We unfortunately have discussed no such plans, but if that would make developers' lives easier by obviating the slow vulcanization step during development, that goal seems compelling.

**Comment by gar1t** [comment]
I don't actually think that would help, as it seems as soon as you need to touch something outside ES6 module space, you run into problems. I may be missing something though. I wish I was, as this is a huge problem for the adoption of ES6!

It seems the standard approach is to transpile everything over to ES2015, i.e. a vulcanize step, even for browsers that support  ES6 modules natively.

I'll just have to invest in a much much faster computer! :)

Please feel free to close this. It's here for the record and has been very helpful to direct my efforts! If I work out any optimizations for the dev workflow I can write them up in a blog post and comment here.

**Comment by chihuahua** [comment]
@gar1t, indeed if you come up with ways to optimize/streamline the workflow, let us know or tell the world. That would be awesome. And yeah, that sums up our current approach.

Also, in general, feel free to ping us any time about your plugin, especially how we can unblock/assist.
