### ISSUE TITLE
No tensorboard, but recognizes event files when running --inspect

### ISSUE THREAD

**Issue by woonsangcho** [tensorflow/tensorboard#456]
Hello,

When I run this:
```
tensorboard --inspect --logdir=F:\a3c_extension\a3c_github\tensorboard
```
It recognizes the event files shown as 

```
======================================================================
Processing event files... (this can take a few minutes)
======================================================================

Found event files in:
F:\a3c_extension\a3c_github\tensorboard\PongNoFrameskip-v4_a3c_0.0003\auditor_for_worker_0

These tags are in F:\a3c_extension\a3c_github\tensorboard\PongNoFrameskip-v4_a3c_0.0003\auditor_for_worker_0:
audio -
histograms -
images -
scalars
   Stats/batch_loss
   Stats/batch_policy_loss
   Stats/batch_value_loss
   Stats/distribution_of_action_0
   Stats/distribution_of_action_1
   Stats/distribution_of_action_2
   Stats/distribution_of_action_3
   Stats/distribution_of_action_4
   Stats/distribution_of_action_5
   Stats/length
   Stats/score
tensor -
======================================================================

Event statistics for F:\a3c_extension\a3c_github\tensorboard\PongNoFrameskip-v4_a3c_0.0003\auditor_for_worker_0:
audio -
graph -
histograms -
images -
scalars
   first_step           0
   last_step            13656005
   max_step             13656005
   min_step             0
   num_steps            54225
   outoforder_steps     []
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -
tensor -
======================================================================
```
So the files are there. Now when I run the following to visualize in tensorboard:
```
 tensorboard --logdir=F:\a3c_extension\a3c_github\tensorboard --host=127.0.0.1 --port=6006
```

It shows
```
Starting TensorBoard b'54' at http://127.0.0.1:6006
(Press CTRL+C to quit)
```

and opening in a browser shows tensorboard, but with no information i.e. No scalar data was found. etc.
No graph information as well.

Please let me know why this is so. Thank you!

**Comment by wchargin** [comment]
The general advice that I would give here is to avoid using drive letters (`F:\`) in the `--logdir` specification, as TensorBoard uses the colon as a separator. (We consider this a bug—https://github.com/tensorflow/tensorboard/issues/52—but this is how it is right now.) So, normally, I'd suggest `cd`ing into `F:\a3c_extension\a3c_github\` and just passing `--logdir tensorboard`.

However, the fact that `--inspect` yields working data surprises me to some degree. Would you mind trying the above anyway? If that works, then it's just a manifestation of the aforelinked known bug. Otherwise, we can continue to investigate.

**Comment by woonsangcho** [comment]
cd ing to the directory solved the problem. Thank you!

**Comment by codingbunny111** [comment]
Hi, 
I have same issue. I can view event files but on the browser it says unable to connect.
