### ISSUE TITLE
Subscribe auto/manual reload actions inside plugin context

### ISSUE THREAD

**Issue by Kingwl** [tensorflow/tensorboard#4829]
Hi folks.

We have a plugin that using our own API (And our own fetch logic). But we cannot detect any actions who emitted in the tensorboard container.

We could add event listeners on the refresh icon. But we have no idea about the auto reload.

Are there any existed way(Might some callback? hooks? etc.) to subscribe the `[Core] Auto Reload` or/and `[Core] User Triggered Reload` actions inside a plugin?

Thanks!

**Comment by psybuzz** [comment]
Thanks for the report, it's nice to hear you are building your own TensorBoard plugin!

> We could add event listeners on the refresh icon

The only supported way to build a custom TensorBoard plugin right now is via the "[dynamic plugin](https://github.com/tensorflow/tensorboard/blob/master/ADDING_A_PLUGIN.md)" system, which embeds the custom plugin in an iframe.  In that scenario, custom plugins should be unable to directly add listeners to the refresh button in the TensorBoard header.

However, we have received multiple requests to introduce a `setOnReloadFired` that is made available to dynamic plugins, so that they can subscribe to the reload events.  See https://github.com/tensorflow/tensorboard/issues/2357#issuecomment-714169048.  We currently don't have the dynamic plugin library published in a easy-to-use way, but assuming that we did, would providing a `setOnReloadFired`, covering both manual/automatic reloads, address your use case?

**Comment by Kingwl** [comment]
> custom plugins should be unable to directly add listeners to the refresh button in the TensorBoard header.

Yep. My fault.

>would providing a setOnReloadFired.

May consider just `postMessage` ? Sorry I'm not familiar enough about the tensorboard.

**Comment by psybuzz** [comment]
The dynamic plugin API currently does not have a great "how to access the API" story at the moment.  Since the addition of this new `setOnReloadFired` requires some digging around the internals of TensorBoard and interop between Angular and Polymer, I will take a look.

The existing `setOnRunsChanged` shares some similarity, but that one does not touch Angular, which is where `setOnReloadFired` needs to get its events.
https://github.com/tensorflow/tensorboard/blob/master/tensorboard/components/experimental/plugin_lib/runs.ts

**Comment by psybuzz** [comment]
Thanks to @stephanwlee for working on this in https://github.com/tensorflow/tensorboard/pull/4846!  Now that that PR landed, custom plugins loaded with the latest `tb-nightly` pip package should be able to listen for reload events.

The exact details on how a custom plugin should do that require some explaining, as we do not have any instructions in the documentation for how to use the plugin API.

To use the API within a custom plugin, one needs to:

- Get the entry point in [tensorboard/components/experimental/plugin_lib/index.ts](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/components/experimental/plugin_lib/index.ts)
- Bundle it with one's favorite bundler (e.g. rollup, webpack, parcel, esbuild)
- Serve the bundled script from your custom plugin's backend and import it on the frontend
- Call the API methods from their appropriate namespace, e.g. `setOnReload` is exposed on `mylib.core.setOnReload()`, while getting runs is exposed on `mylib.runs.getRuns()`

In PR, https://github.com/tensorflow/tensorboard/pull/4850, there is an example of how to do so with Bazel in particular.

Since we are missing some docs, please feel free to ask questions.

**Comment by Kingwl** [comment]
Thanks! And also thanks @stephanwlee !

**Comment by arghyaganguly** [comment]
@Kingwl , please confirm if this can be closed.Thanks.

**Comment by Kingwl** [comment]
Sorry, I haven't test the latest API yet. 
But I think we could just close this one. We could easily reopen (or create another one) and track If there's any others issue in the future.
