### ISSUE TITLE
load file failed

### ISSUE THREAD

**Issue by ranjiewwen** [tensorflow/tensorboard#517]
- although i use can launch tensorboard 'python -m tensorboard.main --logdir "${MODEL_DIR}" --port 8080'

- but i meet another proble: it load file failed

![20170912111826](https://user-images.githubusercontent.com/9885492/30306705-54b1f234-97ac-11e7-84ae-5064d0044ae3.png)
- and the flie is in the exist
![20170912111912](https://user-images.githubusercontent.com/9885492/30306714-64663bb8-97ac-11e7-9478-ef6a20ecfa18.png)

**Comment by ranjiewwen** [comment]
- i run other demo meet the same problem. there is not graph or scalars ,image ... exist

**Comment by chihuahua** [comment]
To clarify, is the problem that you are seeing no active dashboards (scalars, images, etc)? And nothing appears in the projector?

If you're using an absolute path for the logdir argument, could you try switching to a relative path (instead of `C:\ ...`, try `TensorFlow\tmp` after entering the `DeepLearning` directory ?

**Comment by ranjiewwen** [comment]
- you can see this problem
- tensorboard had active
- absolute path use ,and file is in the directory; but 6006 web can't load file

![20170912162918](https://user-images.githubusercontent.com/9885492/30315773-9ffec4da-97d7-11e7-8c4b-a499b5117db3.png)

**Comment by chihuahua** [comment]
Interesting ... so from the projector dashboard, if you click Load Data and then select metadata, it won't load?

**Comment by gowtham-kp** [comment]
@ranjiewwen  Is this still an issue or is it resolved. If its resolved, Can I close the issue?
