### ISSUE TITLE
Tensorboard local IP address error

### ISSUE THREAD

**Issue by ghost** [tensorflow/tensorboard#549]
Tensorboard says that I should connect to 0.0.0.0:6006 but in reality, 127.0.0.1:6006 should be used. My colleague tells me that it only happens on Windows. Maybe say "Starting at 0.0.0.0:6006 **and** 127.0.0.1:6006". Thanks in advance! I love tensorboard! Thanks for developing it!

**Comment by bileschi** [comment]
It appears that others also have this problem.

https://stackoverflow.com/questions/44175037/cant-open-tensorboard-0-0-0-06006-or-localhost6006

**Comment by wchargin** [comment]
We’ve fixed a number of edge cases like this one since this issue was
filed, including a bunch of changes to our network logic (e.g., #1449,
#2589). It’s quite possible that there still exist configurations in the
wild that we’re not handling correctly. If you’re still running into
this on the latest version of TensorBoard, please post back to this
issue and we’ll reopen it, or file a new one if it looks like a
different problem. Thanks!
