### ISSUE TITLE
ERROR: TensorBoard must be run as superuser to bind to port 6006

### ISSUE THREAD

**Issue by GF-Huang** [tensorflow/tensorboard#5808]
![image](https://user-images.githubusercontent.com/4510984/179565490-79a9440f-9ef5-4165-ad6a-5d78e075975c.png)

**Comment by bileschi** [comment]
This error message is raised if TensorBoard is unable to connect to a port due to an access error [EACCES](https://docs.python.org/3/library/errno.html#errno.EACCES).

This can happen if some other software is governing access to that port on your setup.  Are you running other software which may be limiting access?  You may be able to try a different port using the `--port` option.

**Comment by GF-Huang** [comment]
After reboot OS, issue disappear.
