### ISSUE TITLE
Can't delete tensorboard logs even with administrator privileges 

### ISSUE THREAD

**Issue by jstiegerstanford** [tensorflow/tensorboard#5895]
Hi 

I'm trying to delete tensorboard log folders and files and I am unable to do this even with administrator privileges.
I am working with windows 10 and have WSL2 installed.
1. try to delete folder -> you'll need administrator permission ->elevate permission (continue) -> you need permission from WIN\\(username)
2. try to change folder permissions -> an error occurred when applying security information to \events.out.tfevents... failed to enumerate objects in the container access is denied
3. in WSL2/cmd/anaconda prompt: sudo rm -r dir-name,  sudo rm -rf dir-name-> "No such file or directory, directory not empty"

Do you have any idea what is going on here? Any advice on how I can fix this problem?
Thanks!

**Comment by jstiegerstanford** [comment]
Computer restart resolved this issue

**Comment by Zugidor** [comment]
### **Explanation:**

This happens when a file (like a tensorboard log) is locked by a running background process (such as python.exe in a conda environment for example).

### **Fix:**

You must stop the process locking the file to make it possible to access, move or delete it. You can use software like [LockHunter](https://lockhunter.com/) to identify and stop the misbehaving process(es) to unlock the file. Most of the time, restarting the computer works too as this also stops the locking process, as long as the locking process doesn't auto-restart itself and re-lock the file.
