### ISSUE TITLE
Correct tensorboard's TF stub to actually match TF

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorboard#6080]
## Environment information (required)

Not related.

## Issue description

Tensorboard's TF stub has a tf.io.gfile module [tensorboard/compat/tensorflow_stub/io/gfile.py](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/compat/tensorflow_stub/io/gfile.py) but it currently deviates quite a lot from the one in TF  (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/lib/io/file_io.py)

Most notable difference:
* There are APIs in the stub that don't actually exist in TF, e.g. `tf.io.gfile.get_filesystem`
* There are APIs in `tf.io.gfile` that are missing in the stub, e.g. `tf.io.gfile.join`

The first problem is most problematic because a (open source) user would expect the stub to be a subset of official TF. Due to the first problem, a user might use the wrong API from TB, but their code will fail once they install TF.

This has caused problems like https://github.com/pytorch/pytorch/issues/30966 and https://github.com/pytorch/pytorch/issues/47139

**Comment by yatbear** [comment]
Looks like the problems linked above are resolved. 

Googlers, please see cl/493955796 for the full discussion (and thanks @ppwwyyxx for the change).

**Comment by ppwwyyxx** [comment]
Yeah, the problem was resolved, although I think it's still nice to fix he mismatch of APIs. Otherwise TB's `tensorflow_stub` is not technically a tensorflow stub.

**Comment by nfelt** [comment]
That's fair, and I agree the stub isn't really a "proper" stub, but it was never really meant to be that - it was basically a temporary hack that we haven't managed to move off of. Rather than trying to keep it aligned with tf.io.gfile's API (which is a moving target), a more principled fix would be to refactor it into a proper API and then make a tf.io.gfile implementation of that API, which would make it more obvious that it's not mean to be a complete stub. This is already tracked in #5286.
