### ISSUE TITLE
Dataloader time shown as 0 in tensor board

### ISSUE THREAD

**Issue by deepanker13** [tensorflow/tensorboard#6136]
Issue → PyTorch profiler not capturing Dataloader time and runtime. Always shows 0.
Code used → I have used the code given in official PyTorch profiler documentation ( [PyTorch documentation](https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html))

Hardware Used-> Nvidia AI100 gpu
PyTorch version-> 1.13.0+cu117
PyTorch tensorboard profiler version → 0.4.1
<img width="1495" alt="Screenshot 2023-01-10 at 12 56 58 AM" src="https://user-images.githubusercontent.com/121787544/211510344-3f75056f-14ac-4ad5-8eaa-054673964051.png">

**Comment by deepanker13** [comment]
HI, @JamesHollyer can you please help me out here.

**Comment by JamesHollyer** [comment]
I am not super familiar with the Profiler Plugin. I know there is now a different repo for it(https://github.com/tensorflow/profiler). Looking at that documentation it is clear that the repo is focused on Tensorflow's profiler. If anyone here can help you @nfelt would be the guy.

**Comment by nfelt** [comment]
@deepanker13 it looks like you're using the Pytorch Profiler plugin, which is a third-party plugin for TensorBoard, and we are not able to provide any user support for those because it's not our code.

I'd suggest consulting the docs at https://github.com/pytorch/kineto and filing an issue there if need be.
