### ISSUE TITLE
Loosen google-auth-oauthlib

### ISSUE THREAD

**Issue by LarsDu** [tensorflow/tensorboard#6197]
The `google-auth-oauthlib` version contraints are rather tight which makes it difficult to install tensorboard in certain environments.
https://github.com/tensorflow/tensorboard/blob/master/tensorboard/pip_package/requirements.txt#L22

I was wondering whether this is intentional as this version of oauthlib is rather old....
google-auth-oauthlib >= 0.4.1, < 0.5

**Comment by arcra** [comment]
Hi,

Up until somewhat recently, we had a flow still relying on an auth flow (namely out of band, aka OOB) that was [deprecated from version 0.5.0](https://github.com/googleapis/google-auth-library-python-oauthlib/releases/tag/v0.5.0), but since that's no longer the case (#6107 ), we should be able to upgrade.

The google-auth-oauthlib library does warn of a breaking change in their [latest release](https://github.com/googleapis/google-auth-library-python-oauthlib/releases/tag/v1.0.0), so we'll need to verify that our use cases are not broken, and possibly submit a fix if necessary when we upgrade (or possibly at least upgrade to a newer, version, but not the latest one).

I'll try to find some time to do this soon. I can't promise a specific timeline, sorry, but I'll keep this on my TODO list.

**Comment by TNonet** [comment]
Hi @arcra, I am also facing this issue. Thank you for your willingness to look at this soon.

**Comment by notac** [comment]
@arcra - this is interfering with our ability to upgrade critical packages in our system. Is there anything we can do to assist?

**Comment by arcra** [comment]
I just merged the change #6246 , but in order for users to benefit from this, they'll need to wait until we do a patch release with this change.

As an alternative, you can use the [`tb-nightly`](http://pypi.org/project/tb-nightly/) package, with a version with this change, which should be anyone produced after tonight.

I'll update this thread whenever I do the patch release cherry-picking this change.

**Comment by TNonet** [comment]
Hi @arcra,

Do you have any update on when the patch version will be released? This is a pretty stringent dependency requirement on `google-auth-oauthlib` and it is preventing us from maintaining up-to-date versions of  `tensorflow` and `pandas-gbq` both of which are core google libraries.

**Comment by arcra** [comment]
Hello folks, I just uploaded the patch release ([version 2.12.1](http://pypi.org/project/tensorboard/2.12.1/)), with the dependency bump.

Let us know if you encounter any issues.

**Comment by TNonet** [comment]
Thank you! This unblocked us!
