### ISSUE TITLE
Issues with Release 2.15.0

### ISSUE THREAD

**Issue by ibaris** [tensorflow/tensorboard#6651]
I'd like to provide some feedback on the latest release of the software. While I appreciate the efforts put into it, there are some aspects that make it feel more like a beta release rather than a stable one. Here are a few observations:

1. **Visual Chunkiness**: The user interface seems to have become bulkier compared to previous versions, which affects the overall user experience.

2. **Dark Mode Issues**: In the dark mode design, there are readability issues with text on buttons, particularly the "Next" and "Previous" buttons.

3. _**Data Table Persistence**: I've noticed that I cannot disable the new data table at the bottom of the plots, which can be inconvenient._ **Edit**: I found out, that the *Enable step selection and data table* was selected by default. 

4. **Matplotlib Image Display**: Images generated with Matplotlib do not appear correctly within the application.

5. **TensorBoard Behavior**: When TensorBoard refreshes, the left column table containing all the experiments jumps to the top, which can be problematic when working with a large number of experiments.

6. **Sorting**: The sorting of the experiments seems to be wrong. I have 150 experiments and the sorting is like: 1, 100, 101, ... 

I hope these observations can help improve the software's usability and stability in future releases. Thank you for your hard work!

**Comment by JamesHollyer** [comment]
Thank you so much for your feedback. Many of these changes are due to an Angular mandate to move from the "legacy" material components. 

1. This is the new look for Angular Material Components. I do not think it looks that bad. If you have any specific examples we may be able to look into it.
2. Sorry we missed those! I will address this ASAP.
3. Yes, we turned that on by default. I hope it is not too inconvenient to disable. Your disabled selection will persist. You can also turn off the table for individual charts by clicking the little "x" in the step selector fob.
4. This is confusing. I am not sure why those images would be affected. Could you share a screenshot of what is happening?
5. I didn't even know we had that behavior previously. I will look into this.
6. Oops! This is a problem and I will address it.

As I said many of these issues are from the mandated Angular Material Components update. However, some are due to the new Runs Table which has a lot more functionality as well as the ability to add much more functionality in future versions. Currently the only way to access that new functionality is to log hparams(here is a demo showing how that is done https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/hparams/hparams_demo.py). In future versions these features will be even more accessible. I hope you find them useful!

If you find any other problems we missed please add them here and I will take a look

**Comment by JamesHollyer** [comment]
I think all of the addressable issues have been dealt with. The only remaining issue the matplotlib image display. I have asked for some more details here. If you can provide a screenshot or some more details please do so and reopen this issue.  

Thanks again for the feedback!
