### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by busFred** [tensorflow/tensorboard#6808]
`google.protobuf.json_format.MessageToJson()` `including_default_value_fields` argument has been deprecated and removed since protobuf v5.26. need to use `always_print_fields_with_nopresence instead.
https://github.com/tensorflow/tensorboard/blob/71952d6a3188a553a18af6cba378bba8303b66c6/tensorboard/plugins/hparams/hparams_plugin.py#L148
https://github.com/protocolbuffers/protobuf/commit/26995798757fbfef5cf6648610848e389db1fecf#diff-8de817c14d6a087981503c9aea38730b1b3e98f4e306db5ff9d525c7c304f234L89-L94
temporary fix is to just downgrade protobuf to 4.25

**Comment by DeepDuke** [comment]
@busFred TKS! Downgrading protobuf to 4.25 works.

**Comment by arcra** [comment]
Thanks for flagging this.

Looks like the new parameter was added less than 2 months ago in protocolbuffers/protobuf#15703, so it would only be present in very recent versions of protobuf dependencies, which might be a bit restrictive.

For now, I'll add a restriction for the protobuf dependency to be < 5.0.0, and eventually we can update it to use the new parameter when we need to bump this dependency again for some reason.

**Comment by wimglenn** [comment]
@arcra  Adding the upper bound [like that](https://github.com/tensorflow/tensorboard/pull/6814/files) is not really a great solution, because any reasonable solver with a constraint on protobuf>=5 will just go ahead and backtrack from tensorboard v2.17.0 to v2.16.2, and then remain broken. 

A more compatible way to solve this is [detect protobuf version](https://docs.python.org/3/library/importlib.metadata.html#distribution-versions) and fix the call into `json_format.MessageToJson` conditionally depending on protobuf 4.x or 5.x.
