### ISSUE TITLE
Sliders on Histograms

### ISSUE THREAD

**Issue by leksandrs** [tensorflow/tensorboard#6877]
I want to visualize a List[List[List[float]]] as a histogram. add_histogram currently accepts a global_step param, so maybe transform that into a local_step and make a global_step that controls a slider (think of the slider that controls the global_step in add_figure)?

Essentially, I want to avoid having a histogram for each outer **List**[List[List[float]]], which feels like it should be possible given that histograms currently draw the steps within the figure (which means that there is room for an outer step).

**Comment by arcra** [comment]
Hello @leksandrs , can you clarify a few things to understand the request? What `add_histogram` method are you referring to? From what API? Same for `add_figure`.

Can you add details for how the nested list is meant to be interpreted, and what needs to be transformed into a `local step`? What do you mean by a "local step"?

**Comment by leksandrs** [comment]
Hey @arcra ! I'm mistaken for having opened an issue here, as I was working with pytorch's tensorboard. For what it's worth, though, by `local step` I meant `steps` in the histogram image below. The `global step` would be the slider value (second image) under this framework.

The inner List[float] will be made into a histogram for each item in the middle List[**List**[List[float]]]. And each item in the outer list will correspond to a bunch of histograms.

The use case is something like this: For each epoch, for each langevin dynamics step, derive some array of float to be made into a histogram. One wants to visualize the progression of histograms across LD steps and across epochs (without flattening the epoch dimension).

![image](https://github.com/tensorflow/tensorboard/assets/69468068/c9987eec-93a6-4d76-96c4-c16feb0df7ce)

![image](https://github.com/tensorflow/tensorboard/assets/69468068/da8ef045-a083-442f-bf35-fdc66f889a5e)

**Comment by arcra** [comment]
I see. The tool generally supports a single concept of a step, and as I understand, this is usually related to the number of epochs. It seems to me like this "local" and "global" step is a specific case related to how you define your training, I don't know how well we could generalize this concept.

I imagine this would even make it a bit harder to see some sort of progression over the "global step", if that's what you intend, because with the slider you would only see one at a time, opposed to e.g. using a different tag for each of those (although I understand they wouldn't be logically related, other than by the tag name).

I'm leaning towards closing this FR, as I don't think it can be a general feature (or perhaps I'm not fully understanding how it's meant to be used). If you think it would still be valuable and there might be other people interested, feel free to open it again, and people can chime in.

**Comment by zimonitrome** [comment]
I think the terminology of global vs. local step comes from histograms having something called a step, while figures also have something called a step, while they are kinda used/visualized in different ways.

If we want to support the current way step works in histograms while also adding a slider then we would need this local/global step arguments (or rather "z-step" vs. "slider step").

I also find myself wanting a slider on histograms. I think it can be difficult to see any single slice of the current visualization.

My request FR would be to change it from the stacked slice view to only display a single histogram with a slider.
