### ISSUE TITLE
No sdist available on pypi

### ISSUE THREAD

**Issue by mhbkb** [tensorflow/tensorboard#689]
Could you add a sdist to pypi? A source tarball will help us integrate `tensorboard` to our current pipeline.

**Comment by jart** [comment]
I would love to, but I'm not sure if it's possible. I'm not sure if setuptools would be able to build TensorBoard. Would you be able to tell me more about your pipeline?

**Comment by mhbkb** [comment]
We are depending on https://github.com/linkedin/pygradle to build our python product which now doesn't support wheel builds/dependencies.

**Comment by jart** [comment]
The TensorBoard team is able to offer strong support for standards. [PEP 427 -- The Wheel Binary Package Format 1.0](https://www.python.org/dev/peps/pep-0427/) was approved for standardization in 2012 by the Python BDFL and his editorial team. The PyGradle project would benefit from supporting it. I would recommend filing an issue with them, because it's unlikely we would be able to provide buildable source distributions on PyPi anytime soon. However, we do use [Bazel](https://bazel.build/) so you can obtain the source from GitHub and use that. Thank you for reaching out with your concerns.
