### ISSUE TITLE
Smoothed curves have a kink in them

### ISSUE THREAD

**Issue by ruuda** [tensorflow/tensorboard#711]
After upgrading to Tensorboard 1.0.0a6 (from PyPI), I started seeing kinks in smoothed graphs. These give the impression that the value suddenly changed at a much faster rate, but in fact the kinks are an artefact of the smoothing algorithm; the kink moves with the smoothing factor:

![smoothing-900-circle](https://user-images.githubusercontent.com/506953/32542059-c4d12408-c471-11e7-9296-9f98bab5ef03.png)
![smoothing-925-circle](https://user-images.githubusercontent.com/506953/32542062-c4e6d2da-c471-11e7-9638-51f25b8dcb15.png)
![smoothing-95-circle](https://user-images.githubusercontent.com/506953/32542058-c4bd8218-c471-11e7-83f0-02eee5a237e5.png)

From top to bottom, a smoothing factor of 0.9, 0.925, and 0.95.

I did not see those kinks with the version I used before. Unfortunately I have no record of which version I was using before 1.0.0a6. In that version the tail of the curve was also smoothed, unlike in 1.0.0.0a6 where the last smoothed point coincides with the last data point.

**Comment by jart** [comment]
Thanks for the report. Is there any chance you could try building TensorBoard from source at HEAD and seeing if this still happens?

```sh
git clone git@github.com:tensorflow/tensorboard
cd tensorboard
bazel build //tensorboard/pip_package:build_pip_package
./bazel-bin/tensorboard/pip_package/build_pip_package /tmp/tensorboard
pip install --upgrade /tmp/tensorboard/*py2*
```

I ask because @alexirpan recently contributed a change to the smoothing algorithm https://github.com/tensorflow/tensorboard/pull/639

Also please note that TensorBoard 1.0.0a6 was published by a contributor in the community. The official pip package is `tensorflow-tensorboard`, although we're in the process of migrating it over to `tensorboard` on PyPi.

**Comment by ruuda** [comment]
With TensorBoard 071f10547833d53e8a0936b5d3997a445f2c73c4 I no longer observe the kink, consider it fixed. Thanks!

> Also please note that TensorBoard 1.0.0a6 was published by a contributor in the community. The official pip package is `tensorflow-tensorboard`.

Thanks for pointing that out, I was not aware of that.
