### ISSUE TITLE
TensorBoard feature request: Search for Node.

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#76]
This issue had been migrated from tensorflow/tensorflow#2730.

> I have been trying to retrain the inception v3 network and TensorBoard has been the only real way to introspect the network and it's implementation so far.
> 
> It would be very useful to be able to find nodes in the graph, by name or other properties. E.g. in my case I am interested in seeing the total_loss node that is being defined here: https://github.com/tensorflow/models/blob/master/inception/inception/inception_train.py#L120 To get a greater idea of what it is linked to.
>

**Comment by Wakeupbuddy** [comment]
would support the proposal of searching by name, like ctrl-F in the webpage.

**Comment by jart** [comment]
Re: @Wakeupbuddy's note, I agree, but such a path must be taken with very special caution.

1. It's almost always a good idea to seamlessly interop with the tools that already exist, since folks already understand them.

2. There's been instances in the past where this has been a suboptimal solution. For example, it is not possible for me to Ctrl+F through the comments attached to a Google Doc.

**Comment by jart** [comment]
We feel this issue should be solved. Chi won't be able to work on it this quarter. I'm marking contributions welcome, since this would be a good opportunity for someone in the community to get their feet wet. If so, please reach out to us on this issue, and we'll help guide you through the process.

**Comment by chihuahua** [comment]
As of Saturday, 4/14, users who install TensorBoard's nightly build (`pip install tb-nightly`) will be able to use the node search feature introduced by #1130.
