### ISSUE TITLE
tensorboard not working

### ISSUE THREAD

**Issue by TalkIsCheapGiveMeMoney** [tensorflow/tensorboard#802]
You haven’t written any scalar data to your event files.
TensorBoard can’t find your event files

**Comment by nfelt** [comment]
This isn't enough to describe a TensorBoard bug.  If you think it's not working because of a bug, please re-open with much more detail (like the TensorFlow code you're using to write the event files, and the version of TensorBoard you're using, and how you're launching TensorBoard).

For general support questions, you can try StackOverflow with the tensorboard tag.

**Comment by TalkIsCheapGiveMeMoney** [comment]
# op to write logs to Tensorboard
    summary_writer = tf.summary.FileWriter(logs_path,
                                            graph=tf.get_default_graph())

  tensorboard --inspect --logdir e:/tmp/tensorflow_logs   The command results are as follows
the tensorboard  version is 0.4.0rc3  and the tensorflow version is 1.4.0


These tags are in e:/tmp/tensorflow_logs\example:
audio -
histograms
   Model/relu1
   Model/relu2
   W1_0
   W1_0/gradient
   W2_0
   W2_0/gradient
   W3_0
   W3_0/gradient
   b1_0
   b1_0/gradient
   b2_0
   b2_0/gradient
   b3_0
   b3_0/gradient
images -
scalars
   accuracy
   loss
tensor -
======================================================================

Event statistics for e:/tmp/tensorflow_logs\example:
audio -
graph
   first_step           0
   last_step            0
   max_step             0
   min_step             0
   num_steps            1
   outoforder_steps     []
histograms
   first_step           0
   last_step            13749
   max_step             13749
   min_step             0
   num_steps            13750
   outoforder_steps     [(13749, 0)]
images -
scalars
   first_step           0
   last_step            13749
   max_step             13749
   min_step             0
   num_steps            13750
   outoforder_steps     [(13749, 0)]
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -
tensor -
======================================================================

**Comment by nfelt** [comment]
Duplicate of #52

**Comment by nfelt** [comment]
Thanks for the additional details.  This is caused by dropping the drive name from the path, see #52 and #789 for more information and a workaround.

I believe the issue should be resolved at HEAD: https://github.com/tensorflow/tensorboard/issues/52#issuecomment-349521326

If you're able to, give that a try, otherwise the next release should resolve this.
