### ISSUE TITLE
Google Cloud Platform Tensorboard - No dashbords are currently active

### ISSUE THREAD

**Issue by kannan60** [tensorflow/tensorboard#829]
Hey guys! So, I have been trying to visualize the data on tensorboard after creating the training and evaluation jobs on cloud. I keep getting this blank page saying no dashboards are currently active. I have explained in detail on the following link on StackOverflow. 

https://stackoverflow.com/questions/47887063/google-cloud-platform-tensorboard-no-dashbords-are-currently-active

Any help would be much appreciated.

Thanks!

**Comment by chihuahua** [comment]
I don't see any events files within the data directory: https://i.stack.imgur.com/dxHAg.png
Events files are named similar to `events.out.tfevents.1510709527.*`.

What are the contents of `gs://weeddetection/train` and `gs://weeddetection/eval?`

**Comment by kannan60** [comment]
@chihuahua I am using GCP for the first time. Sorry, I might sound like a novice. Thank you so much for your help in advance :)

I followed the instructions on this link: 
https://medium.com/google-cloud/object-detection-tensorflow-and-google-cloud-platform-72e0a3f3bdd6

The contents of gs://weeddetection/train/packages/3ec30d866964baa26dd523360aed8221aa24ebaa4c527d34bf10fedbf2baf456 are:
1. object_detection-0.1.tar.gz
2.   slim-0.1.tar.gz

I do not have a folder for eval. How do I get the events files into the data directory?

**Comment by chihuahua** [comment]
Hmm, TensorBoard dashboards become active after reading relevant events files. Are there any in the `train` directory? If not, we can think about why summaries aren't being written to it.

Thank you for the info!

**Comment by kannan60** [comment]
@chihuahua yes, as you can see from the previous screenshots, there aren't any event files even in the `train `directory.  However, when i did the training locally, I had all these files in the training directory:

![training_local](https://user-images.githubusercontent.com/31975295/34236621-86915be8-e64c-11e7-9a3d-193076f1b153.JPG)

It says the training the evaluation jobs are queued? Does that mean I have to do something to start the training in the cloud? Could there be any issues with the version of TF or Cloud SDK installed? If there was, the training would not have queued, right?

**Comment by nfelt** [comment]
It sounds like TensorBoard not showing any data is just a symptom of the jobs not actually running - or at least, not getting far enough to produce an `events.out.tfevents.*` file, since without the events file TensorBoard won't show anything.  I'm going to close this out since it doesn't sound like a TensorBoard bug, but feel free to reopen if you can get the events file to appear and TensorBoard is still not rendering anything.

Re: why the jobs aren't running, I'm afraid we can't be much help with Cloud ML Engine since it's a different product, but if your jobs are queued for a long time maybe it's an issue with not having enough resources to run them?  E.g. https://cloud.google.com/ml-engine/docs/troubleshooting#job_queued_for_a_long_time  You could also try adding the [google-cloud-ml](https://stackoverflow.com/questions/tagged/google-cloud-ml) tag to your StackOverflow question.
