### ISSUE TITLE
Can I manual set the event file name in python script?

### ISSUE THREAD

**Issue by EmmaW8** [tensorflow/tensorboard#849]
To initialize tensorboard in python, we need to set  log path by 
```
logswriter = tf.summary.FileWriter
self.logs_path = "./log_tf"
self.summary_writer = logswriter(self.logs_path)
```

But the event file name are not clearly specified, so while training we can get an event file like this:
`events.out.tfevents.1514896554.gpu7.cse.cuhk.edu.hk`

under `./log_tf` folder.

As you can see, there is no rule for the name. When I train several times, I often forget which event file corresponding to which model. 
How can I manage this name problem?
Does any one has better solution?

**Comment by chihuahua** [comment]
Unfortunately, the names of events are auto-generated. However, you can use the `filename_suffix` argument of `tf.summary.FileWriter` to append a suffix.

Each directory should probably contain events files for the same model because TensorBoard breaks down when multiple file writers write events files within the same directory.

**Comment by EmmaW8** [comment]
@chihuahua 
Thanks a lot.
