### ISSUE TITLE
Visualize more than just images with Tensorboard?

### ISSUE THREAD

**Issue by serfaniane** [tensorflow/tensorboard#983]
Is there a way to visualize more than just images with Tensorboard, say for example a video that is being generated with a GAN?

**Comment by nfelt** [comment]
Duplicate of #39

**Comment by nfelt** [comment]
I'm closing this out as a dupe of #39 since we already have an open feature request for first-class video summary support.  Note however though the last comment of #39 which is that GIFs are actually rendered in TensorBoard's images plugin today: https://github.com/tensorflow/tensorboard/issues/39#issuecomment-360906712

So if your videos are pretty short, that could be one workaround.
